# Generated by Django 5.0.7 on 2026-02-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscriptionplan_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='caption',
            field=models.TextField(blank=True, default='', verbose_name="Qo'shimcha ma'lumot"),
        ),
    ]
