# Generated by Django 5.0.7 on 2026-02-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscriptionplan_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='once_per_center',
            field=models.BooleanField(default=True),
        ),
    ]
