# Generated by Django 5.0.7 on 2026-02-19 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_center_capacity_limit'),
        ('billing', '0004_promocode_once_per_center'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centersubscription',
            options={'ordering': ('-plan__tier', '-expires_at')},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ('tier', 'monthly_price')},
        ),
        migrations.AddField(
            model_name='centersubscription',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centersubscription',
            name='remaining_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Pauza qilinganda qolgan vaqt (sekund)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tier',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Daraja (Tier)'),
        ),
        migrations.AlterField(
            model_name='centersubscription',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.center'),
        ),
        migrations.AlterField(
            model_name='centersubscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PAUSED', 'PAUSED'), ('EXPIRED', 'EXPIRED'), ('BLOCKED', 'BLOCKED')], default='ACTIVE', max_length=20),
        ),
    ]
