# Generated by Django 5.0.7 on 2026-02-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_center_capacity_limit'),
        ('billing', '0005_alter_centersubscription_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='centersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('center',), name='unique_active_center_sub'),
        ),
    ]
