# Generated by Django 5.0.7 on 2026-02-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_centersubscription_unique_active_center_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ruxsatlar (modullar)'),
        ),
    ]
