# Generated by Django 5.0.7 on 2026-02-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_subscriptionplan_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod (unique)')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Qisqa izoh')),
                ('category', models.CharField(choices=[('core', 'Asosiy'), ('students', "O'quvchilar"), ('groups', 'Guruhlar'), ('payments', "Moliya / To'lov"), ('debtors', 'Qarzdorlar'), ('schedule', 'Jadval / Davomat'), ('courses', 'Kurslar / Darslar'), ('staff', 'Xodimlar / Rollar'), ('broadcast', 'SMS / Reklama'), ('reports', 'Hisobot / Export'), ('crm', 'CRM / Analytics'), ('settings', 'Sozlamalar')], default='core', max_length=20, verbose_name='Kategoriya')),
                ('is_core', models.BooleanField(default=False, verbose_name='Asosiy feature?')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'ordering': ('category', 'order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_features',
            field=models.ManyToManyField(blank=True, related_name='plans', to='billing.planfeature', verbose_name='Ruxsatlar (M2M)'),
        ),
    ]
