# Generated by Django 5.0.7 on 2026-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_plan_feature_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='category',
            field=models.CharField(choices=[('core', 'Asosiy Modullar'), ('finance', 'Moliya va Hisobot'), ('marketing', 'Marketing va SMS'), ('team', 'Jamoa va Rollar'), ('advanced', 'Murakkab Tizimlar')], default='core', max_length=20, verbose_name='Kategoriya'),
        ),
    ]
