# Generated by Django 5.0.7 on 2026-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_planfeature_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_12m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='12 oylik narx (jami)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_3m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='3 oylik narx'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_6m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='6 oylik narx'),
        ),
    ]
