# Generated by Django 5.0.7 on 2026-02-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_subscriptionplan_price_12m_subscriptionplan_price_3m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_9m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='9 oylik narx'),
        ),
    ]
