# Generated by Django 5.0.7 on 2026-03-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_subscriptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='click_trans_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
