# Generated by Django 5.0.7 on 2026-03-18 11:51

from django.db import migrations, models


def forwards_fill_amount_and_status(apps, schema_editor):
    SubscriptionRequest = apps.get_model('billing', 'SubscriptionRequest')
    for req in SubscriptionRequest.objects.all().iterator():
        updates = {}
        if not req.amount and req.price:
            updates['amount'] = req.price
        if req.status == 'approved':
            updates['status'] = 'paid'
        elif req.status == 'rejected':
            updates['status'] = 'cancelled'
        if updates:
            SubscriptionRequest.objects.filter(pk=req.pk).update(**updates)


def backwards_fill_price_and_status(apps, schema_editor):
    SubscriptionRequest = apps.get_model('billing', 'SubscriptionRequest')
    for req in SubscriptionRequest.objects.all().iterator():
        updates = {}
        if not req.price and req.amount:
            updates['price'] = req.amount
        if req.status == 'paid':
            updates['status'] = 'approved'
        elif req.status == 'cancelled':
            updates['status'] = 'rejected'
        if updates:
            SubscriptionRequest.objects.filter(pk=req.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_click_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(forwards_fill_amount_and_status, backwards_fill_price_and_status),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
