# Generated by Django 5.0.7 on 2026-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_subscriptionrequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='merchant_trans_id',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
    ]
