# Generated by Django 5.0.7 on 2026-03-18 12:43

import django.db.models.deletion
from django.db.models import Q
from django.db import migrations, models


def forwards_fill_plan(apps, schema_editor):
    SubscriptionRequest = apps.get_model("billing", "SubscriptionRequest")
    SubscriptionPlan = apps.get_model("billing", "SubscriptionPlan")

    for req in SubscriptionRequest.objects.filter(plan__isnull=True).iterator():
        plan_name = (req.plan_name or "").strip()
        if not plan_name:
            continue
        plan = (
            SubscriptionPlan.objects.filter(
                Q(code__iexact=plan_name) | Q(name__iexact=plan_name) | Q(title__iexact=plan_name),
                active=True,
            )
            .order_by("-id")
            .first()
        )
        if plan:
            SubscriptionRequest.objects.filter(pk=req.pk).update(plan_id=plan.id)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_subscriptionrequest_merchant_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_requests', to='billing.subscriptionplan'),
        ),
        migrations.RunPython(forwards_fill_plan, migrations.RunPython.noop),
    ]
