# Generated by Django 5.0.7 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0017_subscriptionrequest_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

