# Generated by Django 5.0.7 on 2026-03-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_paymenttransaction_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='promo_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
