# Generated by Django 5.0.7 on 2026-04-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0019_subscriptionrequest_promo_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_branches",
            field=models.PositiveIntegerField(
                default=1,
                help_text="1 = faqat asosiy markaz, 0 = cheksiz",
                verbose_name="Maksimal filiallar soni",
            ),
        ),
    ]
