# Generated by Django 5.2.1 on 2026-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_user_user_center_role_idx_user_user_phone_num_idx"),
        ("billing", "0020_add_parent_center_and_max_branches"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="centersubscription",
            index=models.Index(fields=["center", "status"], name="cent_sub_status_idx"),
        ),
    ]
