# Generated by Django 5.2.1 on 2026-05-06 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_user_user_center_role_idx_user_user_phone_num_idx"),
        ("billing", "0021_centersubscription_cent_sub_status_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planfeature",
            name="description_uz",
            field=models.TextField(blank=True, default="", verbose_name="Tavsif (UZ)"),
        ),
        migrations.AddField(
            model_name="planfeature",
            name="icon",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="Ikonka"
            ),
        ),
        migrations.AddField(
            model_name="planfeature",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Faol"),
        ),
        migrations.AddField(
            model_name="planfeature",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Nomi (EN)"
            ),
        ),
        migrations.AddField(
            model_name="planfeature",
            name="name_ru",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Nomi (RU)"
            ),
        ),
        migrations.AddField(
            model_name="planfeature",
            name="name_uz",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Nomi (UZ)"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="description_uz",
            field=models.TextField(blank=True, default="", verbose_name="Tavsif (UZ)"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_recommended",
            field=models.BooleanField(default=False, verbose_name="Tavsiya etiladi"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="landing_visible",
            field=models.BooleanField(
                default=True, verbose_name="Landingda ko'rsatilsin"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="student_range_uz",
            field=models.CharField(
                blank=True,
                default="",
                max_length=40,
                verbose_name="O'quvchilar diapazoni (UZ)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="subtitle_uz",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="Sarlavha ostidagi matn (UZ)",
            ),
        ),
        migrations.CreateModel(
            name="CenterFeatureOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField()),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_overrides",
                        to="accounts.center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.planfeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Markaz xususiyat override",
                "unique_together": {("center", "feature")},
            },
        ),
    ]
