# Generated by Django 5.0.7 on 2026-05-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0022_planfeature_description_uz_planfeature_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planfeature",
            name="implementation_status",
            field=models.CharField(
                choices=[
                    ("READY", "Tayyor"),
                    ("PARTIAL", "Qisman"),
                    ("PLANNED", "Rejada"),
                ],
                default="READY",
                max_length=10,
                verbose_name="Implementatsiya holati",
            ),
        ),
        migrations.AddField(
            model_name="planfeature",
            name="is_highlight",
            field=models.BooleanField(
                default=False,
                help_text="Landing card'da yuqorida 'asosiy' xususiyat sifatida ko'rinadi",
                verbose_name="Asosiy xususiyat?",
            ),
        ),
        migrations.AddField(
            model_name="planfeature",
            name="show_on_landing",
            field=models.BooleanField(
                default=True, verbose_name="Landing'da ko'rinsin?"
            ),
        ),
    ]
