# Generated by Django 5.0.7 on 2026-06-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0025_add_manual_oy_dars_soni_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="badge_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Karta tepasidagi yorliq, masalan: OMMABOP, ENG KUCHLI",
                max_length=30,
                verbose_name="Badge matni",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="original_price",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Landing'da chizib tashlangan narx (0 = ko'rsatilmaydi)",
                verbose_name="Asl narx (kesib tashlangan)",
            ),
        ),
    ]
