# Generated by Django 5.0.7 on 2026-07-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_center_role_ai_enabled"),
        ("billing", "0026_add_original_price_badge_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="centersubscription",
            name="is_grandfathered",
            field=models.BooleanField(
                default=False,
                help_text="Migratsiyadan oldingi mijoz — tarif o'zgarishlari bo'limlarini olib tashlamaydi",
                verbose_name="Grandfathered (eski shartlar himoyalangan)",
            ),
        ),
        migrations.AddField(
            model_name="planfeature",
            name="type",
            field=models.CharField(
                choices=[
                    ("CORE", "Asosiy (doim ochiq)"),
                    ("BOOLEAN", "Yoq/O'chir"),
                    ("LIMIT", "Limit (raqam)"),
                    ("QUOTA", "Kvota (oyiga)"),
                ],
                default="BOOLEAN",
                help_text="CORE = doim ochiq (qulflab bo'lmaydi), BOOLEAN = yoq/o'chir, LIMIT = raqamli chek, QUOTA = oylik kvota",
                max_length=10,
                verbose_name="Turi",
            ),
        ),
        migrations.CreateModel(
            name="FeatureUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(help_text="YYYY-MM", max_length=7)),
                ("used_count", models.PositiveIntegerField(default=0)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_usages",
                        to="accounts.center",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="billing.planfeature",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["center", "feature", "period"],
                        name="billing_fea_center__31c351_idx",
                    )
                ],
                "unique_together": {("center", "feature", "period")},
            },
        ),
        migrations.CreateModel(
            name="PlanFeatureRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "limit_value",
                    models.PositiveIntegerField(
                        blank=True, help_text="None = cheksiz", null=True
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_rules",
                        to="billing.planfeature",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_rules",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["plan", "feature"],
                        name="billing_pla_plan_id_7be17d_idx",
                    )
                ],
                "unique_together": {("plan", "feature")},
            },
        ),
    ]
