# Generated by Django 5.0.7 on 2025-10-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(blank=True, max_length=100)),
                ('telefon1', models.CharField(max_length=20)),
                ('telefon2', models.CharField(blank=True, max_length=20)),
                ('yosh', models.PositiveIntegerField()),
                ('manba', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('reklama', 'Banner / Reklama'), ('tanish', 'Do‘st / Tanish'), ('boshqa', 'Boshqa')], max_length=50)),
                ('yonalish', models.CharField(choices=[('english', 'Ingliz tili'), ('russian', 'Rus tili'), ('python', 'Python dasturlash'), ('frontend', 'Frontend dasturlash'), ('backend', 'Backend dasturlash'), ('design', 'Grafik dizayn'), ('smm', 'SMM'), ('buxgalteriya', 'Buxgalteriya')], max_length=50)),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
