# Generated by Django 5.0.7 on 2025-10-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_manba_yonalish_alter_lead_manba_alter_lead_yonalish'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Yashash manzili'),
        ),
    ]
