# Generated by Django 5.0.7 on 2025-11-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_leadstatus_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh (comment)'),
        ),
    ]
