# Generated by Django 5.0.7 on 2025-11-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_lead_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-yaratilgan'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-sana'], 'verbose_name': 'Xarid so‘rovi', 'verbose_name_plural': 'Xarid so‘rovlari'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sana'], 'verbose_name': 'Sotuv', 'verbose_name_plural': 'Sotuvlar'},
        ),
        migrations.AddField(
            model_name='product',
            name='sotilgan_soni',
            field=models.PositiveIntegerField(default=0, help_text='Jami sotilgan mahsulotlar soni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='narx_chaqmoq',
            field=models.PositiveIntegerField(help_text='Mahsulot narxi (chaqmoqda)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qoldiq',
            field=models.PositiveIntegerField(default=0, help_text='Ombordagi mahsulot soni'),
        ),
    ]
