# Generated by Django 5.0.7 on 2025-11-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qoldiq',
        ),
    ]
