# Generated by Django 5.0.7 on 2025-11-03 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_qoldiq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasdiqlovchi', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlovchi'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='store.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='sana',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=10, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='O‘quvchi'),
        ),
    ]
