# Generated by Django 5.0.7 on 2026-01-10 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_purchaserequest_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads_by', to=settings.AUTH_USER_MODEL, verbose_name='Kim o‘tkazdi'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to=settings.AUTH_USER_MODEL, verbose_name='O‘quvchi (student)'),
        ),
    ]
