# Generated by Django 5.0.7 on 2026-01-27 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_center_features'),
        ('store', '0011_lead_converted_at_lead_converted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
    ]
