# Generated by Django 5.0.7 on 2026-01-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_center_features'),
        ('store', '0012_product_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='manba',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='sale',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='yonalish',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AlterField(
            model_name='manba',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='yonalish',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='leadstatus',
            unique_together={('nom', 'center')},
        ),
        migrations.AlterUniqueTogether(
            name='manba',
            unique_together={('nom', 'center')},
        ),
        migrations.AlterUniqueTogether(
            name='yonalish',
            unique_together={('nom', 'center')},
        ),
    ]
