# Generated by Django 5.0.7 on 2026-01-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_lead_center_leadstatus_center_manba_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AddField(
            model_name='lead',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi'),
        ),
        migrations.AddField(
            model_name='lead',
            name='jshr',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='JSHR'),
        ),
        migrations.AddField(
            model_name='lead',
            name='otchestvo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Otasining ismi'),
        ),
        migrations.AddField(
            model_name='lead',
            name='passport_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport ID'),
        ),
    ]
