# Generated by Django 5.0.7 on 2026-02-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_center_is_system'),
        ('store', '0014_lead_birth_date_lead_gender_lead_jshr_lead_otchestvo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='narx_som',
            field=models.PositiveIntegerField(default=0, help_text='Mahsulot narxi (so‘mda)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='narx_som',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField(verbose_name="Summa (so'm)")),
                ('izoh', models.CharField(max_length=255, verbose_name='Izoh')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-sana'],
            },
        ),
    ]
