# Generated by Django 5.0.7 on 2026-02-08 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_center_is_system'),
        ('store', '0015_product_narx_som_sale_narx_som_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('plastik', 'Plastik'), ('otkazma', 'O‘tkazma')], default='naqd', max_length=20, verbose_name='To‘lov usuli'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receiver',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Qabul qiluvchi'),
        ),
        migrations.AddField(
            model_name='expense',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hodim'),
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center')),
            ],
            options={
                'verbose_name': 'Xarajat toifasi',
                'verbose_name_plural': 'Xarajat toifalari',
                'unique_together': {('nom', 'center')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.expensecategory', verbose_name='Toifa'),
        ),
    ]
