# Generated by Django 5.0.7 on 2026-02-08 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_expense_payment_method_expense_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='sana',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
