# Generated by Django 5.0.7 on 2026-02-11 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_center_is_system'),
        ('store', '0017_alter_expense_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
    ]
