# Generated by Django 5.0.7 on 2026-03-07 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_comment_center_productimage_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan sana/vaqt"),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_reason',
            field=models.TextField(blank=True, null=True, verbose_name="O'chirish sababi"),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AddField(
            model_name='product',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiklangan sana/vaqt'),
        ),
        migrations.AddField(
            model_name='product',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Tiklagan foydalanuvchi'),
        ),
    ]
