# Generated by Django 5.0.7 on 2026-03-24 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_center_db_credentials'),
        ('education', '0032_dailylightningrecord'),
        ('store', '0019_product_deleted_at_product_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Yaratildi'), ('updated', 'Yangilandi'), ('status_changed', "Status o'zgardi"), ('follow_up_set', 'Follow-up belgilandi'), ('converted', "Studentga o'tkazildi"), ('archived', 'Arxivlandi'), ('trial_scheduled', 'Trial belgilandi'), ('trial_result_changed', "Trial natijasi o'zgardi")], max_length=40)),
                ('from_value', models.CharField(blank=True, default='', max_length=255)),
                ('to_value', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrialLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('attended', models.BooleanField(blank=True, null=True)),
                ('result_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('attended', 'Qatnashdi'), ('absent', 'Kelmagan'), ('converted', "Ro'yxatdan o'tdi"), ('not_interested', 'Qiziqmadi'), ('follow_up_needed', 'Follow-up kerak')], db_index=True, default='pending', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('registered_after_trial', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-scheduled_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TrialLessonActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Yaratildi'), ('updated', 'Yangilandi'), ('result_changed', "Natija o'zgardi"), ('converted', "Studentga o'tdi")], max_length=32)),
                ('from_value', models.CharField(blank=True, default='', max_length=255)),
                ('to_value', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='leadstatus',
            options={'ordering': ('order', 'nom')},
        ),
        migrations.AddField(
            model_name='lead',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_to_student',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='parent_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='code',
            field=models.CharField(blank=True, choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('no_answer', 'Javob bermadi'), ('trial_scheduled', 'Trial belgilandi'), ('trial_attended', 'Trial qatnashdi'), ('registered', "Ro'yxatdan o'tdi"), ('lost', "Yo'qotildi")], db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['center', 'qoshilgan_sana'], name='store_lead_center__22a6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['center', 'status'], name='store_lead_center__54193d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['center', 'assigned_manager'], name='store_lead_center__400450_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['center', 'manba'], name='store_lead_center__485aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['center', 'is_archived'], name='store_lead_center__15b8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['center', 'converted_to_student'], name='store_lead_center__2a5a84_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up_date'], name='store_lead_next_fo_4c5ac8_idx'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='store.lead'),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trial_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_lessons', to='education.group'),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_lessons', to='store.lead'),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_trial_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triallessonactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_lesson_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triallessonactivity',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='triallessonactivity',
            name='trial_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='store.triallesson'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['center', 'action', 'created_at'], name='store_leada_center__cc8a04_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', 'created_at'], name='store_leada_lead_id_b76c87_idx'),
        ),
        migrations.AddIndex(
            model_name='triallesson',
            index=models.Index(fields=['center', 'scheduled_at'], name='store_trial_center__63280d_idx'),
        ),
        migrations.AddIndex(
            model_name='triallesson',
            index=models.Index(fields=['center', 'result_status'], name='store_trial_center__eba3dc_idx'),
        ),
        migrations.AddIndex(
            model_name='triallesson',
            index=models.Index(fields=['teacher', 'scheduled_at'], name='store_trial_teacher_fc38d7_idx'),
        ),
        migrations.AddIndex(
            model_name='triallesson',
            index=models.Index(fields=['lead', 'scheduled_at'], name='store_trial_lead_id_dd9400_idx'),
        ),
        migrations.AddIndex(
            model_name='triallessonactivity',
            index=models.Index(fields=['center', 'action', 'created_at'], name='store_trial_center__96d302_idx'),
        ),
        migrations.AddIndex(
            model_name='triallessonactivity',
            index=models.Index(fields=['trial_lesson', 'created_at'], name='store_trial_trial_l_b5d0e3_idx'),
        ),
    ]
