# Generated by Django 5.0.7 on 2026-03-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_leadactivity_triallesson_triallessonactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Yaratildi'), ('updated', 'Yangilandi'), ('status_changed', "Status o'zgardi"), ('follow_up_set', 'Qayta aloqa belgilandi'), ('converted', "Studentga o'tkazildi"), ('archived', 'Arxivlandi'), ('trial_scheduled', 'Sinov dars belgilandi'), ('trial_result_changed', "Sinov dars natijasi o'zgardi")], max_length=40),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='code',
            field=models.CharField(blank=True, choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('no_answer', 'Javob bermadi'), ('trial_scheduled', 'Sinov dars belgilandi'), ('trial_attended', 'Sinov darsda qatnashdi'), ('registered', "Ro'yxatdan o'tdi"), ('lost', "Yo'qotildi")], db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='result_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('attended', 'Qatnashdi'), ('absent', 'Kelmagan'), ('converted', "Ro'yxatdan o'tdi"), ('not_interested', 'Qiziqmadi'), ('follow_up_needed', 'Qayta aloqa kerak')], db_index=True, default='pending', max_length=24),
        ),
    ]
