# Generated by Django 5.2.1 on 2026-04-30 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_user_child_code"),
        ("education", "0051_alter_enrollment_lesson_pattern"),
        ("store", "0024_migrate_lead_subjects_to_yonalish"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_leads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kim tasdiqladi",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="is_confirmed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="leadstatus",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "Yangi"),
                    ("contacted", "Bog'lanildi"),
                    ("no_answer", "Javob bermadi"),
                    ("trial_scheduled", "Sinovga yozildi"),
                    ("trial_attended", "Sinov darsda qatnashdi"),
                    ("registered", "Tasdiqlandi"),
                    ("lost", "Bekor qilingan"),
                ],
                db_index=True,
                default="",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="LeadGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("min_students", models.PositiveSmallIntegerField(default=1)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("collecting", "Yig'ilmoqda"),
                            ("ready", "Tayyor"),
                            ("converted", "Guruhga aylantirilgan"),
                        ],
                        db_index=True,
                        default="collecting",
                        max_length=16,
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_lead_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.center",
                    ),
                ),
                (
                    "converted_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_lead_groups",
                        to="education.group",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_lead_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_groups",
                        to="education.category",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_groups",
                        to="store.yonalish",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="store.leadgroup",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["center", "lead_group"], name="store_lead_center__8edc30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["center", "is_confirmed"], name="store_lead_center__2a159b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadgroup",
            index=models.Index(
                fields=["center", "status"], name="store_leadg_center__52740f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadgroup",
            index=models.Index(
                fields=["center", "is_archived"], name="store_leadg_center__0132a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadgroup",
            index=models.Index(
                fields=["center", "subject"], name="store_leadg_center__3ec158_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadgroup",
            index=models.Index(
                fields=["center", "department"], name="store_leadg_center__04be6c_idx"
            ),
        ),
    ]
