# Generated by Django 5.0.7 on 2026-05-02 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_parent_telegram_link"),
        ("store", "0027_cleanup_legacy_lead_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=80, verbose_name="To'lov usuli nomi"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="accounts.center",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov usuli",
                "verbose_name_plural": "To'lov usullari",
                "ordering": ["-is_active", "nom"],
                "unique_together": {("center", "nom")},
            },
        ),
    ]
