# Generated by Django 5.0.7 on 2026-06-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0028_paymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="bilim_darajasi",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Bilim darajasi / Sinfi",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="parent_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Ota-onasining ismi",
            ),
        ),
    ]
