# Generated by Codex on 2026-04-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_remove_center_center_slug_deleted_perf_idx_and_more"),
        ("core", "0002_notification_core_notifi_recipie_4e71b2_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileAccessToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key_prefix", models.CharField(db_index=True, max_length=16)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("device_name", models.CharField(blank=True, default="", max_length=120)),
                ("device_platform", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_access_tokens",
                        to="accounts.center",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_access_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mobileaccesstoken",
            index=models.Index(fields=["user", "is_revoked", "expires_at"], name="core_mobile_user_3d310a_idx"),
        ),
        migrations.AddIndex(
            model_name="mobileaccesstoken",
            index=models.Index(fields=["center", "is_revoked"], name="core_mobile_center_22cc7d_idx"),
        ),
    ]
