# Generated by Django 5.2.1 on 2026-04-08 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_remove_center_center_slug_deleted_perf_idx_and_more"),
        ("core", "0003_mobileaccesstoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectorAIChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="Direktor AI chat", max_length=255
                    ),
                ),
                ("launcher_position", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director_ai_chat_sessions",
                        to="accounts.center",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director_ai_chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DirectorAIChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Foydalanuvchi"), ("assistant", "AI")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("source", models.CharField(blank=True, default="", max_length=24)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.directoraichatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="directoraichatsession",
            index=models.Index(
                fields=["center", "updated_at"], name="core_direct_center__d58a47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directoraichatsession",
            index=models.Index(
                fields=["user", "updated_at"], name="core_direct_user_id_0cf87b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="directoraichatsession",
            constraint=models.UniqueConstraint(
                fields=("center", "user"),
                name="core_director_ai_chat_unique_center_user",
            ),
        ),
        migrations.AddIndex(
            model_name="directoraichatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="core_direct_session_4ec7e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directoraichatmessage",
            index=models.Index(
                fields=["role", "created_at"], name="core_direct_role_5e67a6_idx"
            ),
        ),
    ]
