# Generated by Django 5.2.1 on 2026-04-09 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_remove_center_center_slug_deleted_perf_idx_and_more"),
        ("core", "0004_directoraichatsession_directoraichatmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CenterDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("students_count", models.PositiveIntegerField(default=0)),
                ("teachers_count", models.PositiveIntegerField(default=0)),
                ("revenue", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="accounts.center",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["center", "date"], name="core_center_center__2dedc2_idx"
                    ),
                    models.Index(
                        fields=["date", "center"], name="core_center_date_ba68f3_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("center", "date"),
                        name="core_center_daily_metric_unique_center_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("attendance", models.BooleanField(default=False)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "To'langan"),
                            ("partial", "Qisman"),
                            ("debt", "Qarzdor"),
                            ("unknown", "Noma'lum"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_daily_metrics",
                        to="accounts.center",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_student_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["center", "student", "date"],
                        name="core_studen_center__6e265f_idx",
                    ),
                    models.Index(
                        fields=["student", "date"],
                        name="core_studen_student_c5eae7_idx",
                    ),
                    models.Index(
                        fields=["date", "center"], name="core_studen_date_3e19dc_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("center", "student", "date"),
                        name="core_student_daily_metric_unique_center_student_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TeacherDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("students_count", models.PositiveIntegerField(default=0)),
                ("revenue", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_daily_metrics",
                        to="accounts.center",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_teacher_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["center", "teacher", "date"],
                        name="core_teache_center__043684_idx",
                    ),
                    models.Index(
                        fields=["teacher", "date"],
                        name="core_teache_teacher_db813c_idx",
                    ),
                    models.Index(
                        fields=["date", "center"], name="core_teache_date_349a3d_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("center", "teacher", "date"),
                        name="core_teacher_daily_metric_unique_center_teacher_date",
                    )
                ],
            },
        ),
    ]
