# Generated by Django 5.0.7 on 2026-04-11 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_centerdailymetric_studentdailymetric_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receive_coin",
                    models.BooleanField(
                        default=True, verbose_name="Chaqmoq o'zgarishi"
                    ),
                ),
                (
                    "receive_broadcast",
                    models.BooleanField(default=True, verbose_name="Umumiy xabarlar"),
                ),
                (
                    "receive_purchase",
                    models.BooleanField(default=True, verbose_name="Xarid holati"),
                ),
                (
                    "receive_system",
                    models.BooleanField(default=True, verbose_name="Tizim xabarlari"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirishnoma sozlamasi",
                "verbose_name_plural": "Bildirishnoma sozlamalari",
            },
        ),
    ]
