# Generated by Django 5.0.7 on 2026-04-13 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_backfill_archived_at_for_students"),
        ("core", "0006_add_notification_preference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurnRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("high", "Yuqori xavf"),
                            ("medium", "O'rta xavf"),
                            ("low", "Past xavf"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0–100: yuqori = xavfli"
                    ),
                ),
                (
                    "reasons",
                    models.JSONField(default=list, help_text="Xavf sabablari ro'yxati"),
                ),
                (
                    "att_pct",
                    models.SmallIntegerField(
                        default=100, help_text="So'nggi 30 kunlik davomat %"
                    ),
                ),
                (
                    "debt_amount",
                    models.BigIntegerField(
                        default=0, help_text="Joriy qarz summasi (so'm)"
                    ),
                ),
                (
                    "notified",
                    models.BooleanField(
                        default=False, help_text="Menejerga xabar yuborilganmi?"
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("assessed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churn_risks",
                        to="accounts.center",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churn_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Churn Xavfi",
                "verbose_name_plural": "Churn Xavflari",
                "ordering": ["-risk_score"],
                "indexes": [
                    models.Index(
                        fields=["center", "risk_level"],
                        name="core_churnr_center__2a5ca6_idx",
                    ),
                    models.Index(
                        fields=["student", "assessed_at"],
                        name="core_churnr_student_84ab2c_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="churnrisk",
            constraint=models.UniqueConstraint(
                fields=("center", "student"),
                name="core_churn_risk_unique_center_student",
            ),
        ),
    ]
