# Generated by Django 5.2.1 on 2026-05-26 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_center_role_ai_enabled"),
        ("core", "0007_add_churn_risk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="directoraichatsession",
            name="core_director_ai_chat_unique_center_user",
        ),
        migrations.AddIndex(
            model_name="directoraichatsession",
            index=models.Index(
                fields=["center", "user", "updated_at"],
                name="core_direct_center__193356_idx",
            ),
        ),
    ]
