# Generated by Django 5.2.1 on 2026-05-27 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_center_role_ai_enabled"),
        ("core", "0008_ai_chat_multi_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_slug", models.CharField(db_index=True, max_length=32)),
                ("score", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                ("coins_earned", models.PositiveIntegerField(default=0)),
                ("played_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to="accounts.center",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-played_at"],
                "indexes": [
                    models.Index(
                        fields=["center", "student", "game_slug", "played_at"],
                        name="core_gamese_center__24d75d_idx",
                    ),
                    models.Index(
                        fields=["center", "game_slug", "score"],
                        name="core_gamese_center__82e0f1_idx",
                    ),
                    models.Index(
                        fields=["student", "played_at"],
                        name="core_gamese_student_7612e6_idx",
                    ),
                ],
            },
        ),
    ]
