# Generated by Django 5.2.1 on 2026-05-27 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_center_role_ai_enabled"),
        ("core", "0009_game_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalGameConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_slug",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global O'yin Sozlamasi",
                "verbose_name_plural": "Global O'yin Sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="GameSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_suggestions",
                        to="accounts.center",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "O'yin Taklifi",
                "verbose_name_plural": "O'yin Takliflari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CenterGameConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_slug", models.CharField(max_length=32)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "max_coins",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 = standart qiymat ishlatiladi"
                    ),
                ),
                (
                    "min_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 = standart qiymat ishlatiladi"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_configs",
                        to="accounts.center",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_config_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Markaz O'yin Sozlamasi",
                "verbose_name_plural": "Markaz O'yin Sozlamalari",
                "indexes": [
                    models.Index(
                        fields=["center", "game_slug"],
                        name="core_center_center__0884c2_idx",
                    )
                ],
                "unique_together": {("center", "game_slug")},
            },
        ),
        migrations.CreateModel(
            name="StudentGameProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_slug", models.CharField(max_length=32)),
                ("current_level", models.PositiveSmallIntegerField(default=1)),
                ("best_score", models.PositiveIntegerField(default=0)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_game_progress",
                        to="accounts.center",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "O'quvchi O'yin Progressi",
                "verbose_name_plural": "O'quvchi O'yin Progresslari",
                "indexes": [
                    models.Index(
                        fields=["center", "student"],
                        name="core_studen_center__31b123_idx",
                    ),
                    models.Index(
                        fields=["student", "game_slug"],
                        name="core_studen_student_ced71d_idx",
                    ),
                ],
                "unique_together": {("center", "student", "game_slug")},
            },
        ),
    ]
