# Generated by Django 5.2.1 on 2026-05-27 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_center_role_ai_enabled"),
        ("core", "0010_game_management"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_slug", models.CharField(db_index=True, max_length=32)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("question_data", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_questions",
                        to="accounts.center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_game_qs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "O'yin Savoli",
                "verbose_name_plural": "O'yin Savollari",
                "ordering": ["game_slug", "level", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["center", "game_slug", "is_active"],
                        name="core_gamequ_center__e596d0_idx",
                    )
                ],
            },
        ),
    ]
