# Generated by Django 5.2.1 on 2026-05-28 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_center_role_ai_enabled"),
        ("core", "0014_chat_presence_reads"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatmessageread",
            name="core_chatmsgread_unique_message_user",
        ),
        migrations.RemoveConstraint(
            model_name="chatpresence",
            name="core_chatpresence_unique_chat_user",
        ),
        migrations.RemoveConstraint(
            model_name="studentballswallet",
            name="unique_student_balls_wallet",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="core_chatme_chat_id_10edee_idx",
            old_name="core_chatme_chat_id_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessageread",
            new_name="core_chatme_message_c08639_idx",
            old_name="core_chatmr_msg_id_usr_idx",
        ),
        migrations.RenameIndex(
            model_name="chatpresence",
            new_name="core_chatpr_chat_id_0fece7_idx",
            old_name="core_chatp_chat_id_ls_idx",
        ),
        migrations.RenameIndex(
            model_name="studentballswallet",
            new_name="core_studen_center__6a4a8e_idx",
            old_name="core_studen_center__balls_idx",
        ),
        migrations.AddField(
            model_name="chatpresence",
            name="typing_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatattachment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessageread",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="chatpresence",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="gameballsconfig",
            name="min_balls_to_convert",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Minimal ball miqdori (chaqmoqqa almashtrish uchun)",
            ),
        ),
        migrations.AlterField(
            model_name="groupchat",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="studentballswallet",
            name="lifetime_balls",
            field=models.PositiveIntegerField(
                default=0, help_text="Jami qo'shilgan ballar (hech qachon kamaymas)"
            ),
        ),
        migrations.AlterField(
            model_name="studentballswallet",
            name="total_balls",
            field=models.PositiveIntegerField(
                default=0, help_text="Konvertatsiya qilinmagan ballar"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatmessageread",
            unique_together={("message", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="chatpresence",
            unique_together={("chat", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="studentballswallet",
            unique_together={("center", "student")},
        ),
    ]
