# Generated by Django 5.0.7 on 2026-03-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='key',
            field=models.CharField(choices=[('privacy', 'Maxfiylik siyosati'), ('terms', 'Foydalanish shartlari'), ('about', 'Biz haqimizda')], max_length=40, unique=True),
        ),
    ]
