# Generated by Django 5.0.7 on 2026-03-22 16:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_staticpage_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demolead',
            options={'ordering': ['-created_at'], 'verbose_name': "Demo so'rovi", 'verbose_name_plural': "Demo so'rovlari"},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', 'id'], 'verbose_name': "Ko'p so'raladigan savol", 'verbose_name_plural': "Ko'p so'raladigan savollar"},
        ),
        migrations.AlterModelOptions(
            name='featureblock',
            options={'ordering': ['section', 'order', 'id'], 'verbose_name': 'Imkoniyat bloki', 'verbose_name_plural': 'Imkoniyat bloklari'},
        ),
        migrations.AlterModelOptions(
            name='partnerlogo',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Hamkor logosi', 'verbose_name_plural': 'Hamkor logolari'},
        ),
        migrations.AlterModelOptions(
            name='pricingfeature',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Tarif afzalligi', 'verbose_name_plural': 'Tarif afzalliklari'},
        ),
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['duration_months', 'order', 'id'], 'verbose_name': 'Tarif rejasi', 'verbose_name_plural': 'Tarif rejalari'},
        ),
        migrations.AlterModelOptions(
            name='screenshotsection',
            options={'ordering': ['order', 'id'], 'verbose_name': "Ekran ko'rinishi", 'verbose_name_plural': "Ekran ko'rinishlari"},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Sayt sozlamasi', 'verbose_name_plural': 'Sayt sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'ordering': ['key'], 'verbose_name': 'Statik sahifa', 'verbose_name_plural': 'Statik sahifalar'},
        ),
        migrations.AlterModelOptions(
            name='supportcard',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Yordam kartasi', 'verbose_name_plural': 'Yordam kartalari'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Mijoz fikri', 'verbose_name_plural': 'Mijozlar fikri'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Vakansiya', 'verbose_name_plural': 'Vakansiyalar'},
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, verbose_name='Javob (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(blank=True, verbose_name='Javob (RU)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(blank=True, verbose_name='Javob (UZ)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Savol (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Savol (RU)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Savol (UZ)'),
        ),
        migrations.AddField(
            model_name='featureblock',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='featureblock',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='featureblock',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='featureblock',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=180, verbose_name='Qisqa matn (EN)'),
        ),
        migrations.AddField(
            model_name='featureblock',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=180, verbose_name='Qisqa matn (RU)'),
        ),
        migrations.AddField(
            model_name='featureblock',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=180, verbose_name='Qisqa matn (UZ)'),
        ),
        migrations.AddField(
            model_name='featureblock',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sarlavha (EN)'),
        ),
        migrations.AddField(
            model_name='featureblock',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='featureblock',
            name='title_uz',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='pricingfeature',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Matn (EN)'),
        ),
        migrations.AddField(
            model_name='pricingfeature',
            name='text_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Matn (RU)'),
        ),
        migrations.AddField(
            model_name='pricingfeature',
            name='text_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Matn (UZ)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='badge_text_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='Badge matni (EN)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='badge_text_ru',
            field=models.CharField(blank=True, max_length=80, verbose_name='Badge matni (RU)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='badge_text_uz',
            field=models.CharField(blank=True, max_length=80, verbose_name='Badge matni (UZ)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='discount_label_en',
            field=models.CharField(blank=True, max_length=80, verbose_name="Chegirma yorlig'i (EN)"),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='discount_label_ru',
            field=models.CharField(blank=True, max_length=80, verbose_name="Chegirma yorlig'i (RU)"),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='discount_label_uz',
            field=models.CharField(blank=True, max_length=80, verbose_name="Chegirma yorlig'i (UZ)"),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tarif nomi (EN)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tarif nomi (RU)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='name_uz',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tarif nomi (UZ)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='student_range_en',
            field=models.CharField(blank=True, max_length=120, verbose_name="O'quvchi limiti (EN)"),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='student_range_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name="O'quvchi limiti (RU)"),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='student_range_uz',
            field=models.CharField(blank=True, max_length=120, verbose_name="O'quvchi limiti (UZ)"),
        ),
        migrations.AddField(
            model_name='screenshotsection',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='screenshotsection',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='screenshotsection',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='screenshotsection',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sarlavha (EN)'),
        ),
        migrations.AddField(
            model_name='screenshotsection',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='screenshotsection',
            name='title_uz',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle_en',
            field=models.TextField(blank=True, verbose_name='Hero matn (EN)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle_ru',
            field=models.TextField(blank=True, verbose_name='Hero matn (RU)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle_uz',
            field=models.TextField(blank=True, verbose_name='Hero matn (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hero sarlavha (EN)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hero sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hero sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_description_en',
            field=models.TextField(blank=True, verbose_name='Meta tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_description_ru',
            field=models.TextField(blank=True, verbose_name='Meta tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_description_uz',
            field=models.TextField(blank=True, verbose_name='Meta tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta sarlavha (EN)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_cta_text_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='Asosiy CTA (EN)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_cta_text_ru',
            field=models.CharField(blank=True, max_length=60, verbose_name='Asosiy CTA (RU)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_cta_text_uz',
            field=models.CharField(blank=True, max_length=60, verbose_name='Asosiy CTA (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='secondary_cta_text_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='Ikkinchi CTA (EN)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='secondary_cta_text_ru',
            field=models.CharField(blank=True, max_length=60, verbose_name='Ikkinchi CTA (RU)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='secondary_cta_text_uz',
            field=models.CharField(blank=True, max_length=60, verbose_name='Ikkinchi CTA (UZ)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Kontent (EN)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='content_ru',
            field=models.TextField(blank=True, verbose_name='Kontent (RU)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='content_uz',
            field=models.TextField(blank=True, verbose_name='Kontent (UZ)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (EN)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='supportcard',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='Tugma matni (EN)'),
        ),
        migrations.AddField(
            model_name='supportcard',
            name='button_text_ru',
            field=models.CharField(blank=True, max_length=60, verbose_name='Tugma matni (RU)'),
        ),
        migrations.AddField(
            model_name='supportcard',
            name='button_text_uz',
            field=models.CharField(blank=True, max_length=60, verbose_name='Tugma matni (UZ)'),
        ),
        migrations.AddField(
            model_name='supportcard',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='supportcard',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='supportcard',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='supportcard',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sarlavha (EN)'),
        ),
        migrations.AddField(
            model_name='supportcard',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='supportcard',
            name='title_uz',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Lavozim (EN)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name='Lavozim (RU)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_uz',
            field=models.CharField(blank=True, max_length=120, verbose_name='Lavozim (UZ)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='Sharh matni (EN)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='Sharh matni (RU)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_uz',
            field=models.TextField(blank=True, verbose_name='Sharh matni (UZ)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='department_en',
            field=models.CharField(blank=True, max_length=120, verbose_name="Bo'lim (EN)"),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='department_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name="Bo'lim (RU)"),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='department_uz',
            field=models.CharField(blank=True, max_length=120, verbose_name="Bo'lim (UZ)"),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='Ish formati (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type_ru',
            field=models.CharField(blank=True, max_length=60, verbose_name='Ish formati (RU)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type_uz',
            field=models.CharField(blank=True, max_length=60, verbose_name='Ish formati (UZ)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_en',
            field=models.TextField(blank=True, verbose_name='Talablar (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_ru',
            field=models.TextField(blank=True, verbose_name='Talablar (RU)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_uz',
            field=models.TextField(blank=True, verbose_name='Talablar (UZ)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities_en',
            field=models.TextField(blank=True, verbose_name='Vazifalar (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities_ru',
            field=models.TextField(blank=True, verbose_name='Vazifalar (RU)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities_uz',
            field=models.TextField(blank=True, verbose_name='Vazifalar (UZ)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lavozim (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lavozim (RU)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_uz',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lavozim (UZ)'),
        ),
        migrations.AlterField(
            model_name='demolead',
            name='center_name',
            field=models.CharField(max_length=120, verbose_name='Markaz nomi'),
        ),
        migrations.AlterField(
            model_name='demolead',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Rozilik'),
        ),
        migrations.AlterField(
            model_name='demolead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='demolead',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='demolead',
            name='is_contacted',
            field=models.BooleanField(default=False, verbose_name="Bog'lanilgan"),
        ),
        migrations.AlterField(
            model_name='demolead',
            name='note',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='demolead',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Parol'),
        ),
        migrations.AlterField(
            model_name='demolead',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak.", regex='^\\+?998\\d{9}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='demolead',
            name='selected_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_leads', to='marketing.pricingplan', verbose_name='Tanlangan tarif'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Javob'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='featureblock',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='featureblock',
            name='icon',
            field=models.CharField(blank=True, help_text='Masalan: bi bi-people-fill yoki fa-solid fa-chart-line', max_length=60, verbose_name='Ikonka classi'),
        ),
        migrations.AlterField(
            model_name='featureblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/features/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='featureblock',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='featureblock',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='featureblock',
            name='section',
            field=models.CharField(choices=[('feature', 'Imkoniyatlar'), ('integration', 'Integratsiyalar'), ('solution', 'Muammo va yechim')], default='feature', max_length=20, verbose_name="Bo'lim"),
        ),
        migrations.AlterField(
            model_name='featureblock',
            name='subtitle',
            field=models.CharField(blank=True, max_length=180, verbose_name='Qisqa matn'),
        ),
        migrations.AlterField(
            model_name='featureblock',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='image',
            field=models.ImageField(upload_to='marketing/partners/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='url',
            field=models.URLField(blank=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='pricingfeature',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='pricingfeature',
            name='pricing_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='marketing.pricingplan', verbose_name='Tarif'),
        ),
        migrations.AlterField(
            model_name='pricingfeature',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='badge_text',
            field=models.CharField(blank=True, max_length=80, verbose_name='Badge matni'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Joriy narx'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='discount_label',
            field=models.CharField(blank=True, max_length=80, verbose_name="Chegirma yorlig'i"),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='duration_months',
            field=models.PositiveSmallIntegerField(help_text='Masalan: 3, 6, 9, 12', verbose_name='Davomiylik (oy)'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Tavsiya etilgan'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Tarif nomi'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Eski narx'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='student_range',
            field=models.CharField(help_text='Masalan: 0-200 ta', max_length=120, verbose_name="O'quvchi limiti"),
        ),
        migrations.AlterField(
            model_name='screenshotsection',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='screenshotsection',
            name='image',
            field=models.ImageField(upload_to='marketing/screenshots/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='screenshotsection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='screenshotsection',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='screenshotsection',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/site/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/hero/', verbose_name='Hero rasmi'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(blank=True, verbose_name='Hero matn'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hero sarlavha'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/site/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta tavsif'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta sarlavha'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='primary_cta_text',
            field=models.CharField(default='Demo olish', max_length=60, verbose_name='Asosiy CTA matni'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='primary_cta_url',
            field=models.CharField(default='/demo/', max_length=255, verbose_name='Asosiy CTA URL'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='secondary_cta_text',
            field=models.CharField(default="Narxlarni ko'rish", max_length=60, verbose_name='Ikkinchi CTA matni'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='secondary_cta_url',
            field=models.CharField(default='/pricing/', max_length=255, verbose_name='Ikkinchi CTA URL'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='ChaqmoqApp', max_length=120, verbose_name='Sayt nomi'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=models.TextField(verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='key',
            field=models.CharField(choices=[('privacy', 'Maxfiylik siyosati'), ('terms', 'Foydalanish shartlari'), ('about', 'Biz haqimizda')], max_length=40, unique=True, verbose_name='Sahifa kaliti'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='supportcard',
            name='button_text',
            field=models.CharField(default="Ko'rish", max_length=60, verbose_name='Tugma matni'),
        ),
        migrations.AlterField(
            model_name='supportcard',
            name='button_url',
            field=models.URLField(verbose_name='Tugma havolasi'),
        ),
        migrations.AlterField(
            model_name='supportcard',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='supportcard',
            name='icon',
            field=models.CharField(blank=True, max_length=60, verbose_name='Ikonka classi'),
        ),
        migrations.AlterField(
            model_name='supportcard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='supportcard',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='supportcard',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/testimonials/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='center_name',
            field=models.CharField(max_length=120, verbose_name='Markaz nomi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, max_length=120, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(verbose_name='Sharh matni'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='apply_button_text',
            field=models.CharField(default='Ariza topshirish', max_length=60, verbose_name='Ariza tugmasi'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='apply_url',
            field=models.URLField(blank=True, verbose_name='Ariza URL'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Shahar'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.CharField(blank=True, max_length=120, verbose_name="Bo'lim"),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('offline', 'Oflayn'), ('online', 'Onlayn'), ('hybrid', 'Gibrid')], default='offline', max_length=20, verbose_name='Ish formati'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(verbose_name='Talablar'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(verbose_name='Vazifalar'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Lavozim'),
        ),
    ]
