# Generated by Django 5.0.7 on 2026-04-02 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_demolead_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demolead",
            name="password",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Parol (eski)"
            ),
        ),
        migrations.AlterField(
            model_name="demolead",
            name="selected_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demo_leads",
                to="marketing.pricingplan",
                verbose_name="Tanlangan tarif (eski)",
            ),
        ),
    ]
