# Generated by Django 5.2.1 on 2026-04-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_alter_demolead_password_alter_demolead_selected_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="stat_value_1",
            field=models.CharField(
                blank=True,
                default="+24%",
                max_length=20,
                verbose_name="Floating stat 1",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="stat_value_2",
            field=models.CharField(
                blank=True, default="98%", max_length=20, verbose_name="Floating stat 2"
            ),
        ),
    ]
