# Generated by Django 5.2.1 on 2026-05-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0006_sitesetting_stat_value_1_sitesetting_stat_value_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="demolead",
            name="comment",
            field=models.TextField(
                blank=True, verbose_name="Qo'shimcha izoh (foydalanuvchi)"
            ),
        ),
        migrations.AddField(
            model_name="demolead",
            name="students_count",
            field=models.CharField(
                blank=True,
                help_text="Masalan: 50-100 ta, 200 dan ortiq",
                max_length=40,
                verbose_name="O'quvchilar soni",
            ),
        ),
        migrations.AlterField(
            model_name="demolead",
            name="note",
            field=models.TextField(blank=True, verbose_name="Admin izohi"),
        ),
    ]
