# Generated by Django 5.0.7 on 2025-11-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chaqmoq',
            field=models.PositiveIntegerField(default=0, verbose_name='Chaqmoq soni'),
        ),
    ]
