# Generated by Django 5.0.7 on 2025-11-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_chaqmoq'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oqituvchi_foizi',
            field=models.PositiveIntegerField(default=40, verbose_name='O‘qituvchi ulushi (%)'),
        ),
    ]
