# Generated by Django 5.0.7 on 2025-11-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_oqituvchi_foizi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otchestvo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
