# Generated by Django 5.0.7 on 2026-01-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_otchestvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gmail',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Gmail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lavozim',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefon1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefon2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
