# Generated by Django 5.0.7 on 2026-01-26 08:17

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar_alter_user_gmail_alter_user_lavozim_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={},
        ),
        migrations.RemoveField(
            model_name='center',
            name='manzil',
        ),
        migrations.RemoveField(
            model_name='center',
            name='nom',
        ),
        migrations.AddField(
            model_name='center',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='center',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='center',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        ),

        migrations.AddField(
            model_name='center',
            name='max_groups',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='center',
            name='max_users',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='center',
            name='name',
            field=models.CharField(default='Default Center', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='plan',
            field=models.CharField(choices=[('FREE', 'FREE'), ('PRO', 'PRO'), ('ENTERPRISE', 'ENTERPRISE')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='center',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, default="default-center"),
        ),

    ]
