# Generated by Django 5.0.7 on 2026-01-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_center_options_remove_center_manzil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='max_students',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='center',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='plan',
            field=models.CharField(choices=[('START', 'START'), ('STANDARD', 'STANDARD'), ('PRO', 'PRO'), ('PREMIUM', 'PREMIUM'), ('ENTERPRISE', 'ENTERPRISE'), ('FREE', 'FREE')], default='START', max_length=20),
        ),
        migrations.AlterField(
            model_name='center',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
