# Generated by Django 5.0.7 on 2026-01-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_center_max_students_alter_center_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='center',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('BLOCKED', 'BLOCKED')], default='ACTIVE', max_length=12),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='center',
            name='plan',
            field=models.CharField(choices=[('FREE', 'FREE'), ('PRO', 'PRO'), ('ENTERPRISE', 'ENTERPRISE')], default='FREE', max_length=20),
        ),
        migrations.AlterField(
            model_name='center',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
