# Generated by Django 5.0.7 on 2026-01-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_center_options_center_expires_at_center_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
