# Generated by Django 5.0.7 on 2026-01-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_center_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tug‘ilgan sana'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi'),
        ),
        migrations.AddField(
            model_name='user',
            name='jshr',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='JSHR Pinfl'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport ID'),
        ),
    ]
