# Generated by Django 5.0.7 on 2026-01-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_address_user_birth_date_user_gender_user_jshr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='center',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
