# Generated by Django 5.0.7 on 2026-01-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='active',
        ),
        migrations.AddField(
            model_name='center',
            name='monthly_price',
            field=models.PositiveIntegerField(default=0, verbose_name="Oylik to'lov"),
        ),
        migrations.AddField(
            model_name='center',
            name='payment_day',
            field=models.PositiveSmallIntegerField(default=5, verbose_name="To'lov sanasi"),
        ),
        migrations.AddField(
            model_name='center',
            name='trial_ends',
            field=models.DateField(blank=True, null=True, verbose_name='Sinov davri tugashi'),
        ),
        migrations.AlterField(
            model_name='center',
            name='plan',
            field=models.CharField(choices=[('FREE', 'FREE'), ('STANDARD', 'STANDARD'), ('PREMIUM', 'PREMIUM'), ('PRO', 'PRO')], default='FREE', max_length=20),
        ),
    ]
