# Generated by Django 5.0.7 on 2026-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_center_active_center_monthly_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='max_daily_lightning',
            field=models.PositiveIntegerField(default=0, verbose_name='Bir kunda max chaqmoq (0=cheksiz)'),
        ),
    ]
