# Generated by Django 5.0.7 on 2026-01-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_center_max_daily_lightning'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='max_daily_deduction',
            field=models.PositiveIntegerField(default=0, verbose_name='Bir kunda max ayirish (0=cheksiz)'),
        ),
    ]
