# Generated by Django 5.0.7 on 2026-01-31 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_center_max_daily_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='children',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='parents', to=settings.AUTH_USER_MODEL, verbose_name='Farzandlari'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Direktor'), ('manager', 'Manager'), ('teacher', 'O‘qituvchi'), ('student', 'O‘quvchi'), ('parent', 'Ota-ona')], max_length=20),
        ),
    ]
