# Generated by Django 5.0.7 on 2026-01-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_children_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='donation_card_holder',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='center',
            name='donation_card_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='center',
            name='donation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='center',
            name='donation_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='center/qr/'),
        ),
    ]
