# Generated by Django 5.0.7 on 2026-02-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_center_donation_card_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='center',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='center',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='promo_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='promo_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
