# Generated by Django 5.0.7 on 2026-02-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_center_discount_amount_center_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
