# Generated by Django 5.0.7 on 2026-02-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_center_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='is_archived',
        ),
    ]
