# Generated by Django 5.0.7 on 2026-02-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_center_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('BLOCKED', 'BLOCKED'), ('ARCHIVED', 'ARCHIVED')], default='ACTIVE', max_length=12),
        ),
    ]
