# Generated by Django 5.0.7 on 2026-02-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_center_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='is_system',
            field=models.BooleanField(default=False, help_text="Tizim markazi - o'chirib bo'lmaydi"),
        ),
    ]
