# Generated by Django 5.0.7 on 2026-02-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_center_is_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='plan',
            field=models.CharField(default='FREE', max_length=50),
        ),
    ]
