# Generated by Django 5.0.7 on 2026-02-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_center_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='capacity_limit',
            field=models.IntegerField(default=100, verbose_name="O'quvchilar limiti"),
        ),
    ]
