# Generated by Django 5.0.7 on 2026-03-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_phone_number_user_reset_attempts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reset_code_expire',
            new_name='reset_code_expire_at',
        ),
        migrations.AddField(
            model_name='user',
            name='is_telegram_linked',
            field=models.BooleanField(default=False, verbose_name='Telegram Ulangan'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username'),
        ),
    ]
