# Generated by Django 5.0.7 on 2026-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_center_deleted_at_center_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_trash',
            field=models.BooleanField(default=False, verbose_name="Trash bo'limiga kira oladimi?"),
        ),
    ]
