# Generated by Django 5.0.7 on 2026-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_user_can_access_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='manager_can_add_student',
            field=models.BooleanField(default=True, verbose_name="Manager o'quvchi qo'shishi mumkinmi?"),
        ),
        migrations.AddField(
            model_name='center',
            name='manager_can_remove_student',
            field=models.BooleanField(default=True, verbose_name="Manager o'quvchilarni o'chirishi mumkinmi?"),
        ),
        migrations.AddField(
            model_name='center',
            name='teacher_can_add_student',
            field=models.BooleanField(default=False, verbose_name="O'qituvchi o'quvchi qo'shishi mumkinmi?"),
        ),
        migrations.AddField(
            model_name='center',
            name='teacher_can_remove_student',
            field=models.BooleanField(default=False, verbose_name="O'qituvchi o'quvchilarni o'chirishi mumkinmi?"),
        ),
    ]
