# Generated by Django 5.0.7 on 2026-03-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_center_manager_can_add_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditlog',
            name='db_host',
            field=models.CharField(blank=True, help_text='Хост БД центра', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='db_name',
            field=models.CharField(blank=True, help_text='Имя отдельной базы данных центра (PostgreSQL)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='db_password',
            field=models.CharField(blank=True, help_text='Пароль БД центра (TODO: хранить безопасно, использовать env или vault)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='db_port',
            field=models.CharField(blank=True, help_text='Порт БД центра', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='db_user',
            field=models.CharField(blank=True, help_text='Пользователь БД центра', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли центр и его база данных'),
        ),
    ]
