# Generated by Django 5.0.7 on 2026-04-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_perf_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="center",
            name="center_slug_deleted_perf_idx",
        ),
        migrations.RemoveIndex(
            model_name="center",
            name="center_status_perf_idx",
        ),
        migrations.RemoveIndex(
            model_name="center",
            name="center_is_deleted_perf_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_phone_perf_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_role_perf_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_is_archived_perf_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_center_role_perf_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_center_role_arch_idx",
        ),
    ]
