# Generated by Codex on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_remove_center_center_slug_deleted_perf_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Arxivlangan sana"),
        ),
    ]
