# Generated by Django 5.0.7 on 2026-04-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_backfill_archived_at_for_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Filial nomi")),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Manzil"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Telefon"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faolmi?"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Tartib"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="accounts.center",
                        verbose_name="Markaz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filial",
                "verbose_name_plural": "Filiallar",
                "ordering": ("order", "name"),
                "unique_together": {("center", "name")},
            },
        ),
    ]
