# Generated by Django 5.2.1 on 2026-04-14 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Yangi markaz nomi"),
                ),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("approved", "Tasdiqlandi"),
                            ("rejected", "Rad etildi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "telegram_message_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_from_request",
                        to="accounts.center",
                        verbose_name="Yaratilgan markaz",
                    ),
                ),
                (
                    "parent_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_requests",
                        to="accounts.center",
                        verbose_name="Asosiy markaz",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="So'rov beruvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filial so'rovi",
                "verbose_name_plural": "Filial so'rovlari",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DirectorCenterAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_directors",
                        to="accounts.center",
                        verbose_name="Markaz",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        limit_choices_to={"role": "director"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_center_access",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Direktor",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim berdi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Direktor markaz ruxsati",
                "verbose_name_plural": "Direktor markaz ruxsatlari",
                "unique_together": {("director", "center")},
            },
        ),
    ]
