# Generated by Django 5.0.7 on 2026-04-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_branchrequest_directorcenteraccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="parent_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_branches",
                to="accounts.center",
                verbose_name="Asosiy markaz (filial bo'lsa)",
            ),
        ),
    ]
