# Generated by Django 5.2.1 on 2026-04-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_add_parent_center_and_max_branches"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="director_telegram_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
