# Generated by Django 5.2.1 on 2026-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_parent_telegram_link"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["center", "role", "is_archived"], name="user_center_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone_number"], name="user_phone_num_idx"),
        ),
    ]
