# Generated by Django 5.2.1 on 2026-05-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_user_user_center_role_idx_user_user_phone_num_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="instagram_username",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Instagram Username"
            ),
        ),
    ]
