# Generated by Django 5.2.1 on 2026-05-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_center_ai_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="ai_parent_enabled",
            field=models.BooleanField(default=False, verbose_name="AI — Ota-ona uchun"),
        ),
        migrations.AddField(
            model_name="center",
            name="ai_student_enabled",
            field=models.BooleanField(
                default=False, verbose_name="AI — O'quvchi uchun"
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="ai_teacher_enabled",
            field=models.BooleanField(
                default=False, verbose_name="AI — O'qituvchi uchun"
            ),
        ),
    ]
