# Generated by Django 5.0.7 on 2026-07-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_user_alive_phone_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Login uchun. Bo'sh bo'lsa NULL saqlanadi; faol foydalanuvchilar orasida unique.",
                max_length=20,
                null=True,
                verbose_name="Telefon raqami (Login uchun)",
            ),
        ),
    ]
