# Generated by Django 5.0.7 on 2026-07-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_phase10_phone_unique_and_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="game_only",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Faqat o‘yin uchun ro‘yxatdan o‘tgan",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_sub",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="Google hisob ID",
            ),
        ),
    ]
