# Generated by Django 5.2.1 on 2026-08-08 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_user_game_only_user_google_sub"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherCenterAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Izoh"
                    ),
                ),
            ],
            options={
                "verbose_name": "O'qituvchi markaz ruxsati",
                "verbose_name_plural": "O'qituvchi markaz ruxsatlari",
            },
        ),
        migrations.AddField(
            model_name="branchrequest",
            name="target_director",
            field=models.ForeignKey(
                blank=True,
                help_text="Bo'sh bo'lsa filial so'rov beruvchining o'ziga biriktiriladi.",
                limit_choices_to={"role": "director"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_branch_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Biriktiriladigan direktor",
            ),
        ),
        migrations.AddIndex(
            model_name="directorcenteraccess",
            index=models.Index(
                fields=["director", "is_active"], name="dca_dir_active_idx"
            ),
        ),
        migrations.AddField(
            model_name="teachercenteraccess",
            name="center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_teachers",
                to="accounts.center",
                verbose_name="Markaz (filial)",
            ),
        ),
        migrations.AddField(
            model_name="teachercenteraccess",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_teacher_accesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kim berdi",
            ),
        ),
        migrations.AddField(
            model_name="teachercenteraccess",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_center_access_teacher",
                to=settings.AUTH_USER_MODEL,
                verbose_name="O'qituvchi",
            ),
        ),
        migrations.AddIndex(
            model_name="teachercenteraccess",
            index=models.Index(
                fields=["teacher", "is_active"], name="tca_teacher_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachercenteraccess",
            index=models.Index(
                fields=["center", "is_active"], name="tca_center_active_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teachercenteraccess",
            unique_together={("teacher", "center")},
        ),
    ]
