from django.urls import path

from . import mobile_api


urlpatterns = [
    path("health/", mobile_api.mobile_health, name="mobile_health"),
    path("auth/csrf/", mobile_api.mobile_auth_csrf, name="mobile_auth_csrf"),
    path("auth/login/", mobile_api.mobile_auth_login, name="mobile_auth_login"),
    path("auth/logout/", mobile_api.mobile_auth_logout, name="mobile_auth_logout"),
    path("auth/status/", mobile_api.mobile_auth_status, name="mobile_auth_status"),
    path("auth/me/", mobile_api.mobile_me, name="mobile_auth_me"),
    path("auth/change-password/", mobile_api.mobile_auth_change_password, name="mobile_auth_change_password"),
    path("me/", mobile_api.mobile_me, name="mobile_me"),
    path("home/", mobile_api.mobile_role_home, name="mobile_home"),
    path("dashboard/", mobile_api.mobile_dashboard, name="mobile_dashboard"),
    path("attendance/", mobile_api.mobile_attendance, name="mobile_attendance"),
    path("payments/", mobile_api.mobile_payments, name="mobile_payments"),
    path("progress/", mobile_api.mobile_progress, name="mobile_progress"),
    path("profile/", mobile_api.mobile_profile, name="mobile_profile"),
    path("director/home/", mobile_api.mobile_director_home, name="mobile_director_home"),
    path("director/students/", mobile_api.mobile_director_students, name="mobile_director_students"),
    path("director/students/<int:student_id>/", mobile_api.mobile_director_student_detail, name="mobile_director_student_detail"),
    path("director/students/<int:student_id>/add-group/", mobile_api.mobile_director_student_add_group, name="mobile_director_student_add_group"),
    path("director/students/<int:student_id>/remove-group/", mobile_api.mobile_director_student_remove_group, name="mobile_director_student_remove_group"),
    path("director/students/<int:student_id>/set-price/", mobile_api.mobile_director_student_set_price, name="mobile_director_student_set_price"),
    path("director/groups/", mobile_api.mobile_director_groups, name="mobile_director_groups"),
    path("teacher/home/", mobile_api.mobile_teacher_home, name="mobile_teacher_home"),
    path("student/home/", mobile_api.mobile_student_home, name="mobile_student_home"),
    path("parent/home/", mobile_api.mobile_parent_home, name="mobile_parent_home"),
    path("parent/dashboard/", mobile_api.mobile_parent_dashboard, name="mobile_parent_dashboard"),
    path("parent/children/", mobile_api.mobile_parent_children, name="mobile_parent_children"),
    path("parent/children/add/", mobile_api.mobile_parent_children_add, name="mobile_parent_children_add"),
    path("parent/select-child/", mobile_api.mobile_parent_select_child, name="mobile_parent_select_child"),
    path("parent/children/<int:child_id>/attendance/", mobile_api.mobile_parent_child_attendance, name="mobile_parent_child_attendance"),
    path("parent/children/<int:child_id>/payments/", mobile_api.mobile_parent_child_payments, name="mobile_parent_child_payments"),
    path("parent/children/<int:child_id>/progress/", mobile_api.mobile_parent_child_progress, name="mobile_parent_child_progress"),
    path("parent/profile/", mobile_api.mobile_parent_profile, name="mobile_parent_profile"),
    path("parent/profile/avatar/", mobile_api.mobile_parent_profile_avatar, name="mobile_parent_profile_avatar"),
    path("parent/notification-preferences/", mobile_api.mobile_parent_notification_preferences, name="mobile_parent_notification_preferences"),
    path("parent/notifications/", mobile_api.mobile_notifications, name="mobile_parent_notifications"),
    path("parent/notifications/<int:notification_id>/read/", mobile_api.mobile_notification_read, name="mobile_parent_notification_read"),
    path("student/debt/", mobile_api.mobile_student_debt_breakdown, name="mobile_student_debt"),
    path("notifications/", mobile_api.mobile_notifications, name="mobile_notifications"),
    path("notifications/<int:notification_id>/read/", mobile_api.mobile_notification_read, name="mobile_notification_read"),
    path("notifications/read-all/", mobile_api.mobile_notifications_read_all, name="mobile_notifications_read_all"),
    path("billing/status/", mobile_api.mobile_billing_status, name="mobile_billing_status"),
    path("leads/", mobile_api.mobile_leads, name="mobile_leads"),
    path("store/products/", mobile_api.mobile_store_products, name="mobile_store_products"),
    path("chaqmoq/history/", mobile_api.mobile_chaqmoq_history, name="mobile_chaqmoq_history"),
    path("chaqmoq/leaderboard/", mobile_api.mobile_chaqmoq_leaderboard, name="mobile_chaqmoq_leaderboard"),
    path(
        "chaqmoq/students/<int:student_id>/",
        mobile_api.mobile_chaqmoq_student_detail,
        name="mobile_chaqmoq_student_detail",
    ),
    path("store/purchase-requests/", mobile_api.mobile_purchase_requests, name="mobile_purchase_requests"),
    path("store/purchase-requests/create/", mobile_api.mobile_purchase_request_create, name="mobile_purchase_request_create"),

    # Profile (all roles)
    path("profile/avatar/", mobile_api.mobile_profile_avatar, name="mobile_profile_avatar"),

    # Teacher panel
    path("teacher/groups/", mobile_api.mobile_teacher_groups, name="mobile_teacher_groups"),
    path("teacher/groups/<int:group_id>/students/", mobile_api.mobile_teacher_group_students, name="mobile_teacher_group_students"),
    path("teacher/attendance/mark/", mobile_api.mobile_teacher_mark_attendance, name="mobile_teacher_mark_attendance"),
    path("teacher/income/", mobile_api.mobile_teacher_income, name="mobile_teacher_income"),
    path("teacher/chaqmoq/rules/", mobile_api.mobile_teacher_chaqmoq_rules, name="mobile_teacher_chaqmoq_rules"),
    path("teacher/chaqmoq/award/", mobile_api.mobile_teacher_award_chaqmoq, name="mobile_teacher_award_chaqmoq"),
]
