# Generated by Django 5.0.7 on 2026-01-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationcenter',
            name='features',
        ),
        migrations.RemoveField(
            model_name='educationcenter',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='code',
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_chaqmoq',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_store',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_students',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
