# Generated by Django 5.0.7 on 2025-11-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Karta summasi (valyutada yoki so'mda)"),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_currency',
            field=models.CharField(default='UZS', max_length=10, verbose_name='Karta valyutasi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12, verbose_name="Kurs (agar karta valyutada bo'lsa)"),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_amount',
            field=models.PositiveIntegerField(default=0, verbose_name="Naqd summasi (so'mda)"),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_full_paid',
            field=models.BooleanField(default=False, verbose_name="To'liq to'landi (belgi)"),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('mixed', 'Aralash')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='summa',
            field=models.PositiveIntegerField(default=0, verbose_name='To‘lov summasi (so‘mda)'),
        ),
    ]
