# Generated by Django 5.0.7 on 2025-11-05 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_payment_card_amount_payment_card_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vaqt',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
