# Generated by Django 5.0.7 on 2025-09-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_attendance_teacher_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('lang', 'Tillar'), ('it', 'IT')], db_index=True, default='lang', max_length=10),
        ),
    ]
