# Generated by Django 5.0.7 on 2025-11-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_payment_vaqt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
