# Generated by Django 5.0.7 on 2025-09-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_group_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('lang', 'Tillar'), ('it', 'IT')], default='lang', max_length=8),
        ),
    ]
