# Generated by Django 5.0.7 on 2025-11-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_payment_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='kurs_narxi',
            field=models.PositiveIntegerField(default=50000000, help_text='Bir oylik to‘lov (so‘mda)'),
        ),
    ]
