# Generated by Django 5.2.5 on 2025-11-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_group_kurs_narxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.PositiveSmallIntegerField(default=11, verbose_name='Oy'),
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.PositiveSmallIntegerField(default=2025, verbose_name='Yil'),
        ),
    ]
