# Generated by Django 5.0.7 on 2025-11-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_payment_month_payment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='education.enrollment', verbose_name='Yozilish'),
        ),
    ]
