# Generated by Django 5.0.7 on 2025-09-21 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_group_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('tur', models.CharField(choices=[('plus', 'Qo‘shish'), ('minus', 'Ayirish')], max_length=10)),
            ],
            options={
                'verbose_name': 'Qoida',
                'verbose_name_plural': 'Qoidalar',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(default=0)),
                ('sana', models.DateField(default=django.utils.timezone.localdate)),
                ('beruvchi', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='edu_ledgers_as_teacher', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_ledgers', to='education.group')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='edu_ledgers_as_student', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.rule')),
            ],
            options={
                'verbose_name': 'Chaqmoq yozuvi',
                'verbose_name_plural': 'Chaqmoq yozuvlari',
            },
        ),
    ]
