# Generated by Django 5.0.7 on 2025-10-05 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_rule_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='beruvchi',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='group',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='student',
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='education.group')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guruhdagi o‘quvchi',
                'verbose_name_plural': 'Guruhdagi o‘quvchilar',
            },
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
