# Generated by Django 5.0.7 on 2025-11-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_alter_payment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
