# Generated by Django 5.0.7 on 2025-10-05 19:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_remove_ledger_beruvchi_remove_ledger_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['group', 'student'], 'verbose_name': 'Guruhga qo‘shilish', 'verbose_name_plural': 'Guruhga qo‘shilishlar'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.group', verbose_name='Guruh'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='jami_tolangan',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jami to‘langan (so‘mda)'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='kurs_narhi',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kurs narxi (so‘mda)'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='O‘quvchi'),
        ),
    ]
