# Generated by Django 5.0.7 on 2025-11-26 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_enrollment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='active',
        ),
        migrations.AlterField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='education.enrollment', verbose_name='Yozilish'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_payments', to='education.group', verbose_name='Guruh'),
        ),
    ]
