# Generated by Django 5.0.7 on 2025-12-11 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone   # 🔥 Qo‘shildi


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_remove_teacherincome_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='forced',
            field=models.BooleanField(
                default=False,
                verbose_name='Kelmadi – lekin o‘qituvchiga pul yozilsin'
            ),
        ),
        migrations.AddField(
            model_name='teacherincome',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now   # 🔥 To‘g‘ri variant
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherincome',
            name='teacher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name='LessonPayment',
        ),
    ]
