# Generated by Django 5.0.7 on 2026-01-10 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_attendance_forced_teacherincome_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Oy'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.PositiveSmallIntegerField(default=2026, verbose_name='Yil'),
        ),
        migrations.CreateModel(
            name='TuitionMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('fee_amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_months', to='education.enrollment')),
            ],
            options={
                'ordering': ('month',),
                'unique_together': {('enrollment', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='education.payment')),
                ('tuition_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='education.tuitionmonth')),
            ],
            options={
                'ordering': ('tuition_month__month', 'id'),
            },
        ),
    ]
