# Generated by Django 5.0.7 on 2025-10-09 19:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_alter_attendance_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('group', 'student', 'date')},
        ),
    ]
