# Generated by Django 5.0.7 on 2026-01-12 02:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_alter_payment_month_alter_payment_year_tuitionmonth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id'], 'verbose_name': 'To‘lov', 'verbose_name_plural': 'To‘lovlar'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_full_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sana',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vaqt',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='year',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='To‘lov sanasi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='To‘lov vaqti'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='kurs_narhi',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Oylik kurs narxi (so‘mda)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='education.category', verbose_name='Bo‘lim (Category)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='kurs_narxi',
            field=models.PositiveIntegerField(default=500000, help_text='Bir oylik to‘lov (so‘mda)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Karta summasi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12, verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cash_amount',
            field=models.PositiveIntegerField(default=0, verbose_name="Naqd (so'mda)"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='education.enrollment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='summa',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami (so‘mda)'),
        ),
    ]
