# Generated by Django 5.0.7 on 2025-10-14 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaqmoq', '0002_alter_ledger_options_alter_ledger_sana'),
        ('education', '0015_alter_attendance_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(default=0, verbose_name='Ball (musbat yoki manfiy)')),
                ('sana', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beruvchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_given_ledgers', to=settings.AUTH_USER_MODEL, verbose_name='Beruvchi')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_ledgers', to='education.group', verbose_name='Guruh')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_ledgers', to='chaqmoq.rule', verbose_name='Qoida')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='education_ledgers', to=settings.AUTH_USER_MODEL, verbose_name='O‘quvchi')),
            ],
            options={
                'verbose_name': 'Chaqmoq jurnali',
                'verbose_name_plural': 'Chaqmoq jurnallari',
                'ordering': ['-sana', '-created_at'],
            },
        ),
    ]
