# Generated by Django 5.0.7 on 2026-01-27 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_center_options_center_expires_at_center_status_and_more'),
        ('education', '0015_alter_payment_options_remove_payment_is_full_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='payment',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
    ]
