# Generated by Django 5.0.7 on 2025-10-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='sana',
            field=models.DateField(verbose_name='Sana'),
        ),
    ]
