# Generated by Django 5.0.7 on 2026-01-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_center_features'),
        ('education', '0016_attendance_center_enrollment_center_payment_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'center')},
        ),
    ]
