# Generated by Django 5.0.7 on 2025-10-15 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_alter_ledger_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='sana',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana'),
        ),
    ]
