# Generated by Django 5.0.7 on 2026-01-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_category_center_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
    ]
