# Generated by Django 5.0.7 on 2025-10-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_alter_ledger_sana'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
