# Generated by Django 5.0.7 on 2025-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0019_delete_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLightningSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('max_lightning', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kunlik chaqmoq limiti',
                'verbose_name_plural': 'Kunlik chaqmoq limitlari',
            },
        ),
    ]
