# Generated by Django 5.0.7 on 2025-10-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_dailylightningsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='kurs_narxi',
            field=models.PositiveIntegerField(default=0, help_text='Bir oylik to‘lov summasi (so‘mda)'),
        ),
        migrations.AddField(
            model_name='group',
            name='oqituvchi_foiz',
            field=models.PositiveIntegerField(default=40, help_text='O‘qituvchining ulushi foizda (%)'),
        ),
        migrations.AddField(
            model_name='group',
            name='oy_dars_soni',
            field=models.PositiveIntegerField(default=12, help_text='Bir oyda nechta dars bo‘lishi kerak'),
        ),
    ]
