# Generated by Django 5.0.7 on 2026-02-11 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_center_is_system'),
        ('education', '0021_enrollment_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancehistory',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='tuitionmonth',
            unique_together={('enrollment', 'month')},
        ),
        migrations.AddField(
            model_name='attendancehistory',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='dailylightningsetting',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='dars',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='oquvchi',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='oylikhisobot',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='teacherincome',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center'),
        ),
        migrations.AddField(
            model_name='tuitionmonth',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center'),
        ),
        migrations.AlterField(
            model_name='dailylightningsetting',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='attendancehistory',
            unique_together={('center', 'student', 'date'), ('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailylightningsetting',
            unique_together={('center', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='tuitionmonth',
            unique_together={('center', 'enrollment', 'month'), ('enrollment', 'month')},
        ),
    ]
