# Generated by Django 5.0.7 on 2026-02-26 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_center_capacity_limit'),
        ('education', '0022_alter_attendancehistory_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherCompensationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed'), ('PER_STUDENT', 'Per Student'), ('PER_LESSON', 'Per Lesson')], default='PERCENT', max_length=20)),
                ('percent', models.PositiveIntegerField(blank=True, null=True)),
                ('fixed_amount', models.BigIntegerField(blank=True, null=True)),
                ('per_student_amount', models.BigIntegerField(blank=True, null=True)),
                ('per_lesson_amount', models.BigIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
