# Generated by Django 5.0.7 on 2025-10-19 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_alter_group_kurs_narxi_alter_group_oqituvchi_foiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='oqituvchi_foiz',
            field=models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='O‘qituvchi ulushi (%)'),
        ),
    ]
