# Generated by Django 5.0.7 on 2025-10-19 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0023_enrollment_oqituvchi_foiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-sana'], 'verbose_name': 'To‘lov', 'verbose_name_plural': 'To‘lovlar'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='education.enrollment', verbose_name='O‘quvchi kursga yozilganligi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sana',
            field=models.DateField(auto_now_add=True, verbose_name='To‘lov sanasi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='summa',
            field=models.PositiveIntegerField(verbose_name='To‘lov summasi (so‘mda)'),
        ),
    ]
