# Generated by Django 5.0.7 on 2026-02-26 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_center_capacity_limit'),
        ('education', '0023_salarypayout_teachercompensationrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_date', 'center'], name='education_p_paid_da_0d1748_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['group'], name='education_p_group_i_166ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayout',
            index=models.Index(fields=['teacher', 'period_year', 'period_month', 'center'], name='education_s_teacher_33b238_idx'),
        ),
    ]
