# Generated by Django 5.0.7 on 2026-02-26 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_center_capacity_limit'),
        ('education', '0024_payment_education_p_paid_da_0d1748_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherExpectedIncomeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('active_students', models.IntegerField(default=0)),
                ('expected_income', models.BigIntegerField(default=0)),
                ('income_per_student', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['teacher', 'year', 'month', 'center'], name='education_t_teacher_9a5045_idx')],
                'unique_together': {('teacher', 'year', 'month', 'center')},
            },
        ),
    ]
