# Generated by Django 5.0.7 on 2025-10-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0025_teacherincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji yoki belgi masalan 💻 📘 🎨', max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
