# Generated by Django 5.0.7 on 2025-10-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0026_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='education.category', verbose_name='Bo‘lim (Category modeli orqali)'),
        ),
    ]
