# Generated by Django 5.0.7 on 2026-03-09 09:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_user_can_access_trash'),
        ('education', '0027_paymentallocation_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('is_closed', models.BooleanField(default=False, verbose_name='Yopilganmi?')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.center')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moliyaviy oy',
                'verbose_name_plural': 'Moliyaviy oylar',
                'unique_together': {('center', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyFinanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.BigIntegerField(default=0)),
                ('total_expense', models.BigIntegerField(default=0)),
                ('center_profit', models.BigIntegerField(default=0)),
                ('student_count', models.IntegerField(default=0)),
                ('attendance_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='education.financialmonth')),
            ],
            options={
                'verbose_name': 'Oylik moliya snapshoti',
                'verbose_name_plural': 'Oylik moliya snapshotlari',
            },
        ),
        migrations.CreateModel(
            name='StudentGroupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, help_text='Null means currently in the group', null=True)),
                ('kurs_narxi', models.PositiveIntegerField(default=0)),
                ('oqituvchi_foiz', models.PositiveIntegerField(default=0)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_history', to='education.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'O‘quvchi guruh tarixi',
                'verbose_name_plural': 'O‘quvchilar guruh tarixi',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSalarySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.BigIntegerField(default=0)),
                ('attendance_count', models.IntegerField(default=0)),
                ('details', models.JSONField(default=dict, help_text='Breakdown by group and student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_snapshots', to='education.financialmonth')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'O‘qituvchi oylik snapshoti',
                'verbose_name_plural': 'O‘qituvchilar oylik snapshotlari',
                'unique_together': {('teacher', 'financial_month')},
            },
        ),
    ]
