# Generated by Django 5.0.7 on 2025-10-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0027_group_category_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Bo‘lim rasmi'),
        ),
    ]
