# Generated by Django 5.0.7 on 2026-03-11 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0029_tuitionmonth_deleted_at_tuitionmonth_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Kiritgan xodim'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Keldi'), ('absent_excused', 'Sababli (Kelmadi)'), ('absent_unexcused', 'Sababsiz (Kelmadi)')], default='present', max_length=20, verbose_name='Holati'),
        ),
    ]
