# Generated by Django 5.0.7 on 2026-03-11 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0030_attendance_created_at_attendance_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherincome',
            name='center_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Markaz ulushi'),
        ),
        migrations.AddField(
            model_name='teacherincome',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Umumiy aylanma'),
        ),
        migrations.AlterField(
            model_name='teacherincome',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name="O'qituvchi ulushi"),
        ),
        migrations.AlterField(
            model_name='teacherincome',
            name='attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_income_record', to='education.attendance'),
        ),
        migrations.AlterField(
            model_name='teacherincome',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_incomes', to='education.group'),
        ),
        migrations.AlterField(
            model_name='teacherincome',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_incomes', to=settings.AUTH_USER_MODEL),
        ),
    ]
