# Generated by Django 5.0.7 on 2026-03-16 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_center_manager_can_add_student_and_more'),
        ('education', '0031_teacherincome_center_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLightningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance_status', models.CharField(blank=True, default='', max_length=20)),
                ('plus_points', models.IntegerField(default=0)),
                ('minus_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_lightning_records', to='education.group')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_lightning_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunlik chaqmoq yozuvi',
                'verbose_name_plural': 'Kunlik chaqmoq yozuvlari',
                'ordering': ('-date', '-updated_at'),
                'unique_together': {('center', 'group', 'student', 'date'), ('group', 'student', 'date')},
            },
        ),
    ]
