# Generated by Django 5.0.7 on 2026-03-25 00:00

import django.db.models.deletion
import django.core.validators
import django.utils.timezone
import education.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_center_db_credentials'),
        ('education', '0032_dailylightningrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kurs boshlanish sanasi'),
        ),
        migrations.AddField(
            model_name='group',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Davomiyligi (oy)'),
        ),
        migrations.AddField(
            model_name='group',
            name='estimated_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Taxminiy tugash sanasi'),
        ),
        migrations.AddField(
            model_name='group',
            name='estimated_end_date_manual',
            field=models.BooleanField(default=False, verbose_name="Taxminiy sana qo'lda belgilang"),
        ),
        migrations.AddField(
            model_name='group',
            name='lessons_per_week',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Haftalik darslar soni'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_estimation_note',
            field=models.CharField(blank=True, default='Bu sana taxminiy hisob bo‘lib, bayramlar, tadbirlar yoki dars ko‘chirilishlari sabab o‘zgarishi mumkin', max_length=255, verbose_name='Tahmin izohi'),
        ),
        migrations.CreateModel(
            name='CenterExamSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_system_enabled', models.BooleanField(default=False, verbose_name='Imtihon tizimi yoqilganmi')),
                ('exam_every_n_lessons', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Har N-darsda imtihon')),
                ('passing_score_percent', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='O‘tish foizi (%)')),
                ('exam_file_upload_enabled', models.BooleanField(default=True, verbose_name='Imtihon fayl yuklash yoqilganmi')),
                ('exam_result_required', models.BooleanField(default=False, verbose_name='Imtihon natijasi majburiymi')),
                ('optional_task_upload_prompt_enabled', models.BooleanField(default=True, verbose_name='Ixtiyoriy topshiriq so‘rovi yoqilganmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_settings', to='accounts.center')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_exam_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Markaz imtihon sozlamasi',
                'verbose_name_plural': 'Markaz imtihon sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='ExamReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=django.utils.timezone.localdate)),
                ('lesson_number_reference', models.PositiveIntegerField(default=0)),
                ('action', models.CharField(choices=[('yes', 'Ha'), ('no', 'Yo‘q'), ('later', 'Keyinroq')], max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_reminder_logs', to='accounts.center')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_reminder_logs', to='education.group')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_reminder_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imtihon eslatma actioni',
                'verbose_name_plural': 'Imtihon eslatma actionlari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=django.utils.timezone.localdate)),
                ('exam_date', models.DateField(default=django.utils.timezone.localdate)),
                ('lesson_number_reference', models.PositiveIntegerField(default=0)),
                ('exam_sequence_number', models.PositiveIntegerField(default=1)),
                ('teacher_decision', models.CharField(choices=[('yes', 'Ha'), ('no', 'Yo‘q'), ('later', 'Keyinroq')], default='later', max_length=10)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='accounts.center')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='education.group')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-exam_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('teacher_comment', models.TextField(blank=True, default='')),
                ('assignment_description', models.TextField(blank=True, default='')),
                ('exam_date', models.DateField(default=django.utils.timezone.localdate)),
                ('lesson_number_reference', models.PositiveIntegerField(default=0)),
                ('absent_in_exam', models.BooleanField(default=False)),
                ('retake_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='accounts.center')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_results', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='education.group')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='education.examsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_exam_results', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-exam_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ExamResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=education.models.exam_upload_path)),
                ('file_kind', models.CharField(choices=[('work', 'Student Work'), ('task', 'Task Attachment'), ('other', 'Other')], default='work', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='education.examresult')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_exam_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imtihon fayli',
                'verbose_name_plural': 'Imtihon fayllari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EducationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, default='', max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_audit_logs', to='accounts.center')),
            ],
            options={
                'verbose_name': 'Education audit log',
                'verbose_name_plural': 'Education audit logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['center', 'created_at'], name='education_e_center__4c0c72_idx'), models.Index(fields=['action_type', 'created_at'], name='education_e_action__e3a4e3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['center', 'group', 'exam_date'], name='education_e_center__8b6391_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['group', 'lesson_number_reference'], name='education_e_group_i_7fe525_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['center', 'group', 'exam_date'], name='education_e_center__425d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'exam_date'], name='education_e_student_151c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['passed', 'percent'], name='education_e_passed_76e85a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('session', 'student')},
        ),
    ]
