# Generated by Django 5.0.7 on 2026-03-24 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_center_db_credentials'),
        ('education', '0033_group_closed_at_group_closed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='fail_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='examresult',
            name='follow_up_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='examresult',
            name='follow_up_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Follow-up needed'), ('parent_contacted', 'Parent contacted'), ('support_required', 'Support required'), ('reviewed', 'Reviewed')], default='not_required', max_length=32),
        ),
        migrations.AddField(
            model_name='examresult',
            name='follow_up_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='follow_up_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['follow_up_status', 'exam_date'], name='education_e_follow__65aa99_idx'),
        ),
    ]
