# Generated by Django 5.0.7 on 2026-03-24 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_center_db_credentials'),
        ('education', '0034_examresult_fail_reason_examresult_follow_up_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInternalRankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.localdate)),
                ('rank_position', models.PositiveIntegerField(default=0)),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('activity_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('exam_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('homework_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discipline_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lightning_bonus_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_internal_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('explanation_text', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_group_rankings', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_ranking_snapshots', to='accounts.center')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_ranking_snapshots', to='education.group')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='internal_group_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guruh ichki reyting snapshoti',
                'verbose_name_plural': 'Guruh ichki reyting snapshotlari',
                'ordering': ('snapshot_date', 'rank_position', 'id'),
                'indexes': [models.Index(fields=['group', 'snapshot_date', 'rank_position'], name='education_g_group_i_cbac13_idx'), models.Index(fields=['student', 'snapshot_date'], name='education_g_student_c46eb7_idx')],
                'unique_together': {('group', 'student', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_count', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('average_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pass_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('pass_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('attendance_total_lessons', models.PositiveIntegerField(default=0)),
                ('attendance_present_lessons', models.PositiveIntegerField(default=0)),
                ('attendance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('internal_rank_position', models.PositiveIntegerField(blank=True, null=True)),
                ('internal_rank_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('completion_recommendation', models.CharField(choices=[('eligible', 'Eligible'), ('needs_review', 'Needs Review'), ('not_eligible', 'Not Eligible')], default='needs_review', max_length=20)),
                ('recommendation_reason', models.TextField(blank=True, default='')),
                ('ranking_explanation', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_academic_summaries', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_summaries', to='accounts.center')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_summaries', to='education.group')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='academic_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Akademik yakuniy xulosa',
                'verbose_name_plural': 'Akademik yakuniy xulosalar',
                'ordering': ('group', 'student'),
                'indexes': [models.Index(fields=['center', 'completion_recommendation'], name='education_s_center__9fae40_idx'), models.Index(fields=['student', 'group'], name='education_s_student_f2f5c5_idx')],
                'unique_together': {('group', 'student')},
            },
        ),
    ]
