# Generated by Django 5.0.7 on 2026-03-24 20:15

import django.db.models.deletion
import django.utils.timezone
import education.models
import uuid
from django.conf import settings
from django.db import migrations, models


def _table_exists(schema_editor, table_name: str) -> bool:
    return table_name in schema_editor.connection.introspection.table_names()


def _get_column_names(schema_editor, table_name: str) -> set[str]:
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    return {col.name for col in description}


def _add_column_if_missing(schema_editor, table_name: str, columns: set[str], column_name: str, definition_sql: str):
    if column_name in columns:
        return
    qn = schema_editor.quote_name
    schema_editor.execute(
        f"ALTER TABLE {qn(table_name)} ADD COLUMN {qn(column_name)} {definition_sql}"
    )
    columns.add(column_name)


def _ensure_certificate_template_table(apps, schema_editor):
    """
    Safe for drifted DBs:
    - If table does not exist, create from migration state.
    - If legacy table exists, add missing Phase-4 columns and backfill data.
    """
    model = apps.get_model("education", "CertificateTemplate")
    table_name = model._meta.db_table

    if not _table_exists(schema_editor, table_name):
        schema_editor.create_model(model)
        return

    columns = _get_column_names(schema_editor, table_name)
    connection = schema_editor.connection
    qn = schema_editor.quote_name

    template_file_field = model._meta.get_field("template_file")
    template_file_type = template_file_field.db_type(connection)
    file_column = template_file_field.column
    _add_column_if_missing(
        schema_editor,
        table_name,
        columns,
        file_column,
        f"{template_file_type} NULL",
    )

    note_field = model._meta.get_field("note")
    note_type = note_field.db_type(connection)
    _add_column_if_missing(
        schema_editor,
        table_name,
        columns,
        "note",
        f"{note_type} NOT NULL DEFAULT ''",
    )

    uploaded_by_type = model._meta.get_field("uploaded_by").target_field.db_type(connection)
    _add_column_if_missing(
        schema_editor,
        table_name,
        columns,
        "uploaded_by_id",
        f"{uploaded_by_type} NULL",
    )

    if file_column in columns and "template_file" in columns and file_column != "template_file":
        schema_editor.execute(
            f"UPDATE {qn(table_name)} "
            f"SET {qn(file_column)} = {qn('template_file')} "
            f"WHERE ({qn(file_column)} IS NULL OR {qn(file_column)} = '') "
            f"AND {qn('template_file')} IS NOT NULL AND {qn('template_file')} != ''"
        )
    if "created_by_id" in columns and "uploaded_by_id" in columns:
        schema_editor.execute(
            f"UPDATE {qn(table_name)} "
            f"SET {qn('uploaded_by_id')} = {qn('created_by_id')} "
            f"WHERE {qn('uploaded_by_id')} IS NULL"
        )


def _ensure_model_table(apps, schema_editor, model_name: str):
    model = apps.get_model("education", model_name)
    if not _table_exists(schema_editor, model._meta.db_table):
        schema_editor.create_model(model)


def _forwards_ensure_phase4_schema(apps, schema_editor):
    _ensure_certificate_template_table(apps, schema_editor)
    _ensure_model_table(apps, schema_editor, "CertificateRecord")
    _ensure_model_table(apps, schema_editor, "CertificateVerificationLog")
    _ensure_model_table(apps, schema_editor, "GroupClosureWorkflow")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_center_db_credentials'),
        ('education', '0035_phase3_internal_ranking_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CertificateTemplate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=150)),
                        ('template_type', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma')], default='certificate', max_length=20)),
                        ('template_file', models.FileField(db_column='file', upload_to=education.models.certificate_template_upload_path)),
                        ('is_active', models.BooleanField(default=True)),
                        ('note', models.CharField(blank=True, default='', max_length=255)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='accounts.center')),
                        ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_certificate_templates', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Certificate template',
                        'verbose_name_plural': 'Certificate templates',
                        'ordering': ('-updated_at', '-id'),
                    },
                ),
                migrations.CreateModel(
                    name='CertificateRecord',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('certificate_type', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma')], default='certificate', max_length=20)),
                        ('certificate_number', models.CharField(max_length=64, unique=True)),
                        ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                        ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                        ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='draft', max_length=20)),
                        ('recommendation_status', models.CharField(choices=[('eligible', 'Eligible'), ('needs_review', 'Needs Review'), ('not_eligible', 'Not Eligible')], default='needs_review', max_length=20)),
                        ('recommendation_reason', models.TextField(blank=True, default='')),
                        ('approved_at', models.DateTimeField(blank=True, null=True)),
                        ('issued_at', models.DateTimeField(blank=True, null=True)),
                        ('pdf_file', models.FileField(blank=True, null=True, upload_to=education.models.certificate_pdf_upload_path)),
                        ('metadata', models.JSONField(blank=True, default=dict)),
                        ('note', models.TextField(blank=True, default='')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates', to=settings.AUTH_USER_MODEL)),
                        ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.center')),
                        ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='education.group')),
                        ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                        ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                        ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='education.studentacademicsummary')),
                        ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='education.certificatetemplate')),
                    ],
                    options={
                        'verbose_name': 'Certificate record',
                        'verbose_name_plural': 'Certificate records',
                        'ordering': ('-created_at', '-id'),
                    },
                ),
                migrations.CreateModel(
                    name='CertificateVerificationLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                        ('user_agent', models.TextField(blank=True, default='')),
                        ('metadata', models.JSONField(blank=True, default=dict)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='education.certificaterecord')),
                        ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_verification_logs', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Certificate verification log',
                        'verbose_name_plural': 'Certificate verification logs',
                        'ordering': ('-created_at',),
                    },
                ),
                migrations.CreateModel(
                    name='GroupClosureWorkflow',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('open', 'Open'), ('continue', 'Continue'), ('remind_later', 'Remind later'), ('closed', 'Closed')], default='open', max_length=20)),
                        ('decision_date', models.DateField(blank=True, null=True)),
                        ('reminder_date', models.DateField(blank=True, null=True)),
                        ('closed_at', models.DateTimeField(blank=True, null=True)),
                        ('note', models.TextField(blank=True, default='')),
                        ('metadata', models.JSONField(blank=True, default=dict)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_closure_workflows', to='accounts.center')),
                        ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_group_workflows', to=settings.AUTH_USER_MODEL)),
                        ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure_workflow', to='education.group')),
                    ],
                    options={
                        'verbose_name': 'Group closure workflow',
                        'verbose_name_plural': 'Group closure workflows',
                        'ordering': ('-updated_at', '-id'),
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(_forwards_ensure_phase4_schema, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['center', 'template_type', 'is_active'], name='education_c_center__dba7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterecord',
            index=models.Index(fields=['center', 'group', 'status'], name='education_c_center__5825b3_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterecord',
            index=models.Index(fields=['certificate_number'], name='education_c_certifi_d7b256_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterecord',
            index=models.Index(fields=['student', 'group'], name='education_c_student_e84a08_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateverificationlog',
            index=models.Index(fields=['created_at'], name='education_c_created_98814c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupclosureworkflow',
            index=models.Index(fields=['center', 'status'], name='education_g_center__b920f0_idx'),
        ),
        migrations.AddIndex(
            model_name='groupclosureworkflow',
            index=models.Index(fields=['decision_date'], name='education_g_decisio_ce9cfd_idx'),
        ),
    ]
