# Generated by Django 5.0.7 on 2026-03-24 20:32

import django.core.validators
from django.db import migrations, models


def _table_exists(schema_editor, table_name: str) -> bool:
    return table_name in schema_editor.connection.introspection.table_names()


def _get_column_names(schema_editor, table_name: str) -> set[str]:
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    return {col.name for col in description}


def _sql_literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def _add_column_if_missing(schema_editor, table_name: str, columns: set[str], column_name: str, definition_sql: str):
    if column_name in columns:
        return
    qn = schema_editor.quote_name
    schema_editor.execute(
        f"ALTER TABLE {qn(table_name)} ADD COLUMN {qn(column_name)} {definition_sql}"
    )
    columns.add(column_name)


def _repair_center_exam_setting_schema(apps, schema_editor):
    model = apps.get_model("education", "CenterExamSetting")
    table_name = model._meta.db_table
    if not _table_exists(schema_editor, table_name):
        schema_editor.create_model(model)
        return

    columns = _get_column_names(schema_editor, table_name)
    connection = schema_editor.connection
    qn = schema_editor.quote_name

    for field_name in (
        "failed_student_threshold",
        "minimum_certificate_attendance_percent",
        "minimum_certificate_average_percent",
    ):
        field = model._meta.get_field(field_name)
        default_sql = _sql_literal(field.get_default())
        _add_column_if_missing(
            schema_editor,
            table_name,
            columns,
            field.column,
            f"{field.db_type(connection)} NOT NULL DEFAULT {default_sql}",
        )
        schema_editor.execute(
            f"UPDATE {qn(table_name)} SET {qn(field.column)} = {default_sql} "
            f"WHERE {qn(field.column)} IS NULL"
        )


def _repair_exam_session_schema(apps, schema_editor):
    model = apps.get_model("education", "ExamSession")
    table_name = model._meta.db_table
    if not _table_exists(schema_editor, table_name):
        schema_editor.create_model(model)
        return

    columns = _get_column_names(schema_editor, table_name)
    connection = schema_editor.connection
    qn = schema_editor.quote_name

    teacher_decision = model._meta.get_field("teacher_decision")
    teacher_decision_default = _sql_literal(teacher_decision.get_default())
    _add_column_if_missing(
        schema_editor,
        table_name,
        columns,
        teacher_decision.column,
        f"{teacher_decision.db_type(connection)} NOT NULL DEFAULT {teacher_decision_default}",
    )
    schema_editor.execute(
        f"UPDATE {qn(table_name)} SET {qn(teacher_decision.column)} = {teacher_decision_default} "
        f"WHERE {qn(teacher_decision.column)} IS NULL"
    )

    decision_note = model._meta.get_field("decision_note")
    decision_note_default = _sql_literal(decision_note.get_default())
    _add_column_if_missing(
        schema_editor,
        table_name,
        columns,
        decision_note.column,
        f"{decision_note.db_type(connection)} NOT NULL DEFAULT {decision_note_default}",
    )
    schema_editor.execute(
        f"UPDATE {qn(table_name)} SET {qn(decision_note.column)} = {decision_note_default} "
        f"WHERE {qn(decision_note.column)} IS NULL"
    )

    updated_by = model._meta.get_field("updated_by")
    _add_column_if_missing(
        schema_editor,
        table_name,
        columns,
        updated_by.column,
        f"{updated_by.target_field.db_type(connection)} NULL",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0036_phase4_certificate_closure_foundation'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='centerexamsetting',
                    name='failed_student_threshold',
                    field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Past natija threshold'),
                ),
                migrations.AddField(
                    model_name='centerexamsetting',
                    name='minimum_certificate_attendance_percent',
                    field=models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Sertifikat uchun min davomat (%)'),
                ),
                migrations.AddField(
                    model_name='centerexamsetting',
                    name='minimum_certificate_average_percent',
                    field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Sertifikat uchun min o‘rtacha foiz (%)'),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(_repair_center_exam_setting_schema, migrations.RunPython.noop),
        migrations.RunPython(_repair_exam_session_schema, migrations.RunPython.noop),
    ]
