# Generated by Codex on 2026-03-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _table_exists(schema_editor, table_name: str) -> bool:
    return table_name in schema_editor.connection.introspection.table_names()


def _get_column_names(schema_editor, table_name: str) -> set[str]:
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    return {col.name for col in description}


def _sql_literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def _add_column_if_missing(schema_editor, table_name: str, columns: set[str], column_name: str, definition_sql: str):
    if column_name in columns:
        return
    qn = schema_editor.quote_name
    schema_editor.execute(
        f"ALTER TABLE {qn(table_name)} ADD COLUMN {qn(column_name)} {definition_sql}"
    )
    columns.add(column_name)


def _repair_group_closure_schema(apps, schema_editor):
    model = apps.get_model("education", "Group")
    table_name = model._meta.db_table
    if not _table_exists(schema_editor, table_name):
        return

    columns = _get_column_names(schema_editor, table_name)
    connection = schema_editor.connection
    qn = schema_editor.quote_name

    is_closed_field = model._meta.get_field("is_closed")
    is_closed_default = _sql_literal(is_closed_field.get_default())
    _add_column_if_missing(
        schema_editor,
        table_name,
        columns,
        is_closed_field.column,
        f"{is_closed_field.db_type(connection)} NOT NULL DEFAULT {is_closed_default}",
    )
    schema_editor.execute(
        f"UPDATE {qn(table_name)} SET {qn(is_closed_field.column)} = {is_closed_default} "
        f"WHERE {qn(is_closed_field.column)} IS NULL"
    )

    closed_at_field = model._meta.get_field("closed_at")
    _add_column_if_missing(
        schema_editor,
        table_name,
        columns,
        closed_at_field.column,
        f"{closed_at_field.db_type(connection)} NULL",
    )

    closed_by_field = model._meta.get_field("closed_by")
    _add_column_if_missing(
        schema_editor,
        table_name,
        columns,
        closed_by_field.column,
        f"{closed_by_field.target_field.db_type(connection)} NULL",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0037_centerexamsetting_failed_student_threshold_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="group",
                    name="is_closed",
                    field=models.BooleanField(default=False, verbose_name="Yopilganmi?"),
                ),
                migrations.AddField(
                    model_name="group",
                    name="closed_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="group",
                    name="closed_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(_repair_group_closure_schema, migrations.RunPython.noop),
    ]
