# Generated by Django 5.0.7 on 2026-03-25 09:29

import django.db.models.deletion
import education.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0038_sync_group_closure_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSessionTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=education.models.exam_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_files', to='education.examsession')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_exam_session_task_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imtihon sessiya task fayli',
                'verbose_name_plural': 'Imtihon sessiya task fayllari',
                'ordering': ('-created_at',),
            },
        ),
    ]
