# Generated by Django 5.0.7 on 2026-03-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0039_examsessiontaskfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificaterecord',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Sertifikat yozuvi', 'verbose_name_plural': 'Sertifikat yozuvlari'},
        ),
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'ordering': ('-updated_at', '-id'), 'verbose_name': 'Sertifikat shabloni', 'verbose_name_plural': 'Sertifikat shablonlari'},
        ),
        migrations.AlterModelOptions(
            name='certificateverificationlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Sertifikat tekshiruv jurnali', 'verbose_name_plural': 'Sertifikat tekshiruv jurnallari'},
        ),
        migrations.AlterModelOptions(
            name='groupclosureworkflow',
            options={'ordering': ('-updated_at', '-id'), 'verbose_name': 'Guruh yopish jarayoni', 'verbose_name_plural': 'Guruh yopish jarayonlari'},
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='certificate_type',
            field=models.CharField(choices=[('certificate', 'Sertifikat'), ('diploma', 'Diplom')], default='certificate', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='recommendation_status',
            field=models.CharField(choices=[('eligible', 'Mos'), ('needs_review', 'Ko‘rib chiqish kerak'), ('not_eligible', 'Mos emas')], default='needs_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('issued', 'Berilgan'), ('revoked', 'Bekor qilingan')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='template_type',
            field=models.CharField(choices=[('certificate', 'Sertifikat'), ('diploma', 'Diplom')], default='certificate', max_length=20),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='follow_up_status',
            field=models.CharField(choices=[('not_required', 'Talab etilmaydi'), ('pending', 'Nazorat kerak'), ('parent_contacted', 'Ota-ona bilan bog‘lanilgan'), ('support_required', 'Qo‘shimcha yordam kerak'), ('reviewed', 'Ko‘rib chiqilgan')], default='not_required', max_length=32),
        ),
        migrations.AlterField(
            model_name='examresultfile',
            name='file_kind',
            field=models.CharField(choices=[('work', 'O‘quvchi ishi'), ('task', 'Topshiriq fayli'), ('other', 'Boshqa')], default='work', max_length=20),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupclosureworkflow',
            name='status',
            field=models.CharField(choices=[('open', 'Ochiq'), ('continue', 'Davom etadi'), ('remind_later', 'Keyinroq eslatilsin'), ('closed', 'Yopilgan')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentacademicsummary',
            name='completion_recommendation',
            field=models.CharField(choices=[('eligible', 'Mos'), ('needs_review', 'Ko‘rib chiqish kerak'), ('not_eligible', 'Mos emas')], default='needs_review', max_length=20),
        ),
    ]
