# Generated by Django 5.2.1 on 2026-04-13 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_backfill_archived_at_for_students"),
        ("education", "0040_alter_certificaterecord_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Dushanba"),
                            (2, "Seshanba"),
                            (3, "Chorshanba"),
                            (4, "Payshanba"),
                            (5, "Juma"),
                            (6, "Shanba"),
                            (7, "Yakshanba"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("room", models.CharField(blank=True, default="", max_length=60)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="accounts.center",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="education.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dars jadvali",
                "verbose_name_plural": "Dars jadvallari",
                "ordering": ("weekday", "start_time"),
                "unique_together": {("group", "weekday", "start_time")},
            },
        ),
    ]
