# Generated by Django 5.0.7 on 2026-04-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_branch"),
        ("education", "0041_add_group_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="accounts.branch",
                verbose_name="Filial",
            ),
        ),
    ]
