# Generated by Django 5.2.1 on 2026-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0042_group_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_deferred",
            field=models.BooleanField(default=False, verbose_name="Kechiktirilganmi?"),
        ),
    ]
