# Generated by Django 5.2.1 on 2026-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0043_enrollment_is_deferred"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="student_payable_amount",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="O‘quvchidan real olinadigan summa. Bo‘sh bo‘lsa, to‘liq kurs narxi olinadi.",
                null=True,
                verbose_name="O'quvchidan olinadigan summa (so'mda)",
            ),
        ),
    ]
