# Generated by Django 5.2.1 on 2026-04-16 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_center_director_telegram_id"),
        ("education", "0044_enrollment_student_payable_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="max_students",
            field=models.PositiveSmallIntegerField(
                default=15, verbose_name="Maksimal o'quvchi soni"
            ),
        ),
        migrations.CreateModel(
            name="CenterExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rent", "Ijara"),
                            ("salary", "Xodim maoshi"),
                            ("utility", "Kommunal"),
                            ("equipment", "Jihozlar"),
                            ("marketing", "Reklama"),
                            ("other", "Boshqa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
    ]
