# Generated by Django 5.2.1 on 2026-04-16 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_center_director_telegram_id"),
        ("education", "0045_group_max_students_centerexpense"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["center", "is_active", "is_deleted"],
                name="enr_center_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["group", "is_active"], name="enr_group_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "is_active"], name="enr_student_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["center", "is_deleted", "paid_date"],
                name="pay_center_del_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["enrollment", "is_deleted"], name="pay_enr_del_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["tuition_month", "is_deleted"], name="pa_tm_deleted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["payment", "is_deleted"], name="pa_payment_deleted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tuitionmonth",
            index=models.Index(
                fields=["enrollment", "month", "is_deleted"], name="tm_enr_month_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tuitionmonth",
            index=models.Index(
                fields=["center", "month", "is_deleted"], name="tm_center_month_idx"
            ),
        ),
    ]
