# Generated by Django 5.2.1 on 2026-04-21 11:44

import django.core.validators
from django.db import migrations, models
from django.db.models import Q, Sum
from django.utils import timezone


def backfill_enrollment_pricing_fields(apps, schema_editor):
    Enrollment = apps.get_model("education", "Enrollment")
    StudentGroupHistory = apps.get_model("education", "StudentGroupHistory")
    Attendance = apps.get_model("education", "Attendance")
    PaymentAllocation = apps.get_model("education", "PaymentAllocation")

    current_month = timezone.localdate().replace(day=1)
    history_map = {}
    for row in (
        StudentGroupHistory.objects.order_by("student_id", "group_id", "-start_date")
        .values("student_id", "group_id", "start_date")
    ):
        key = (row["student_id"], row["group_id"])
        history_map.setdefault(key, row["start_date"])

    attendance_map = {
        (row["group_id"], row["student_id"]): int(row["cnt"] or 0)
        for row in (
            Attendance.objects.filter(
                date__year=current_month.year,
                date__month=current_month.month,
            )
            .filter(
                Q(status="present")
                | Q(status="absent_unexcused")
                | Q(present=True)
                | Q(forced=True)
            )
            .values("group_id", "student_id")
            .annotate(cnt=models.Count("id"))
        )
    }
    paid_map = {
        row["tuition_month__enrollment_id"]: int(row["total"] or 0)
        for row in (
            PaymentAllocation.objects.filter(tuition_month__month=current_month)
            .values("tuition_month__enrollment_id")
            .annotate(total=Sum("amount"))
        )
    }

    updates = []
    for enrollment in Enrollment.objects.select_related("group").all().iterator():
        joined_at = history_map.get((enrollment.student_id, enrollment.group_id))
        if not joined_at:
            created_at = getattr(enrollment, "created_at", None)
            joined_at = created_at.date() if created_at else timezone.localdate()

        monthly_price = int(
            getattr(enrollment, "kurs_narhi", 0)
            or getattr(enrollment.group, "kurs_narxi", 0)
            or 0
        )
        monthly_lessons = int(getattr(enrollment.group, "oy_dars_soni", 0) or 0)
        custom_amount = getattr(enrollment, "student_payable_amount", None)
        if custom_amount not in (None, "") and int(custom_amount or 0) != monthly_price:
            pricing_type = "custom"
        elif getattr(joined_at, "day", 1) > 1:
            pricing_type = "prorated"
        else:
            pricing_type = "full"

        enrollment.joined_at = joined_at
        enrollment.monthly_price = monthly_price
        enrollment.monthly_lessons = monthly_lessons
        enrollment.pricing_type = pricing_type
        enrollment.active_lessons_count = int(
            attendance_map.get((enrollment.group_id, enrollment.student_id), 0) or 0
        )
        enrollment.paid_amount = int(paid_map.get(enrollment.id, 0) or 0)
        updates.append(enrollment)

    if updates:
        Enrollment.objects.bulk_update(
            updates,
            [
                "joined_at",
                "monthly_price",
                "monthly_lessons",
                "pricing_type",
                "active_lessons_count",
                "paid_amount",
            ],
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0046_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="active_lessons_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Joriy oy uchun avtomatik hisoblangan darslar soni.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Faol darslar soni",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="joined_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Qo'shilgan sana"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="monthly_lessons",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Oydagi darslar soni",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="monthly_price",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Asosiy oylik narx. O'qituvchi va markaz ulushi shu qiymatdan hisoblanadi.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Oylik narx (so'mda)",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="paid_amount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Joriy oy uchun avtomatik hisoblangan to'langan summa.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="To'langan summa",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("full", "To'liq oy"),
                    ("prorated", "Dars bo'yicha"),
                    ("custom", "Admin qo'lda"),
                ],
                default="full",
                max_length=12,
                verbose_name="Narxlash turi",
            ),
        ),
        migrations.RunPython(backfill_enrollment_pricing_fields, noop_reverse),
    ]
