# Generated by Django 5.0.7 on 2026-04-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0050_studentgrouptransfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="lesson_pattern",
            field=models.CharField(
                choices=[
                    ("group", "Avtomatik"),
                    ("even", "Juft kunlari"),
                    ("odd", "Toq kunlari"),
                    ("daily", "Har kuni"),
                ],
                default="group",
                max_length=12,
                verbose_name="Dars patterni",
            ),
        ),
    ]
