# Generated by Django 5.2.1 on 2026-04-30 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_staff_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])
    StaffProfile = apps.get_model("education", "StaffProfile")

    role_map = {
        "teacher": "teacher",
        "manager": "manager",
        "director": "admin",
    }

    for user in User.objects.filter(center__isnull=False).exclude(role__in=["student", "parent"]).iterator():
        full_name = " ".join(
            [
                item.strip()
                for item in [getattr(user, "ism", "") or "", getattr(user, "familya", "") or ""]
                if item and item.strip()
            ]
        ).strip() or getattr(user, "email", "") or ""
        phone = (
            getattr(user, "telefon1", "")
            or getattr(user, "phone_number", "")
            or getattr(user, "telefon2", "")
            or ""
        )
        position = (getattr(user, "lavozim", "") or "").strip()
        if not position:
            position = {
                "teacher": "Ustoz",
                "manager": "Manager",
                "director": "Admin",
            }.get(getattr(user, "role", ""), "Xodim")

        StaffProfile.objects.get_or_create(
            user_id=user.id,
            defaults={
                "tenant_id": user.center_id,
                "full_name": full_name,
                "phone": phone,
                "role": role_map.get(getattr(user, "role", ""), "other"),
                "position": position,
                "is_active": bool(getattr(user, "is_active", True) and not getattr(user, "is_archived", False)),
                "levels": [],
                "directions": [],
                "note": "",
            },
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_parent_telegram_link"),
        ("education", "0051_alter_enrollment_lesson_pattern"),
        ("store", "0027_cleanup_legacy_lead_subject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("teacher", "Ustoz"),
                            ("manager", "Manager"),
                            ("admin", "Admin"),
                            ("other", "Boshqa"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("position", models.CharField(blank=True, default="", max_length=100)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("levels", models.JSONField(blank=True, default=list)),
                ("directions", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True, related_name="staff_profiles", to="store.yonalish"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profiles",
                        to="accounts.center",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Xodim profili",
                "verbose_name_plural": "Xodim profillari",
                "ordering": ("full_name", "id"),
                "indexes": [
                    models.Index(
                        fields=["tenant", "role", "is_active"],
                        name="staffprof_t_role_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Dushanba"),
                            (2, "Seshanba"),
                            (3, "Chorshanba"),
                            (4, "Payshanba"),
                            (5, "Juma"),
                            (6, "Shanba"),
                            (7, "Yakshanba"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[("available", "Bo'sh"), ("busy", "Band")],
                        default="available",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_availabilities",
                        to="accounts.center",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ustoz bandligi",
                "verbose_name_plural": "Ustoz bandliklari",
                "ordering": ("weekday", "start_time", "id"),
                "indexes": [
                    models.Index(
                        fields=["tenant", "teacher", "weekday"],
                        name="teachavail_t_day_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_staff_profiles, noop_reverse),
    ]
