# Generated by Django 5.0.7 on 2026-05-01 05:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_parent_telegram_link"),
        ("education", "0052_staffprofile_teacheravailability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="O'chirilgan"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan sana/vaqt"
                    ),
                ),
                (
                    "deleted_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="O'chirish sababi"
                    ),
                ),
                (
                    "restored_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tiklangan sana/vaqt"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("attendance", "Davomat"),
                            ("homework", "Vazifa"),
                            ("participation", "Ishtirok"),
                            ("test", "Test"),
                            ("penalty", "Jarima"),
                            ("other", "Boshqa"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "score",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Musbat — yaxshi (qo'shiladi), manfiy — yomon (ayriladi).",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_activities",
                        to="accounts.center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan foydalanuvchi",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_activities",
                        to="education.group",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tiklagan foydalanuvchi",
                    ),
                ),
                (
                    "source_attendance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_activities",
                        to="education.attendance",
                    ),
                ),
                (
                    "source_exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_activities",
                        to="education.examresult",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "O'quvchi faoliyati",
                "verbose_name_plural": "O'quvchi faoliyatlari",
                "ordering": ("-date", "-id"),
                "indexes": [
                    models.Index(
                        fields=["student", "date", "is_deleted"],
                        name="sact_student_date_idx",
                    ),
                    models.Index(
                        fields=["center", "date", "is_deleted"],
                        name="sact_center_date_idx",
                    ),
                    models.Index(
                        fields=["student", "type", "date"],
                        name="sact_student_type_date_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="studentactivity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_attendance__isnull", False)),
                fields=("source_attendance",),
                name="sact_unique_per_attendance",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentactivity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_exam__isnull", False)),
                fields=("source_exam",),
                name="sact_unique_per_exam",
            ),
        ),
    ]
