# Generated by Django 5.2.1 on 2026-05-03 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0053_studentactivity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="support_foiz",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Support xodimga ajratiladigan foiz. Asosiy o'qituvchi foizidan ayrimcha.",
                verbose_name="Support foizi (%)",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="support_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Guruh uchun yordamchi (teacher/manager). Tanlanmasa bo'sh qoldiring.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Support xodimi",
            ),
        ),
    ]
