# Generated by Django 5.2.1 on 2026-05-04 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_user_user_center_role_idx_user_user_phone_num_idx"),
        ("education", "0054_group_support_foiz_group_support_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["group", "date"], name="att_group_date_idx"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["center", "date"], name="att_center_date_idx"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["status"], name="att_status_idx"),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["center", "is_archived"], name="group_center_arch_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["oqituvchi", "is_archived"], name="group_oqit_arch_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["support_teacher", "is_archived"], name="group_sup_arch_idx"
            ),
        ),
    ]
