# Generated by Django 5.0.7 on 2026-05-08 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0055_attendance_att_group_date_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="credit_balance",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ortiqcha to’lov (overpayment) miqdori. Keyingi oy fee yozilganda avtomatik ayiriladi.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Hisobidagi pul (so’m)",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="jami_tolangan",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Jami to’langan (so’mda)",
            ),
        ),
    ]
