# Generated by Django 5.2.1 on 2026-05-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_center_role_ai_enabled"),
        ("education", "0056_enrollment_credit_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="kurs_narxi",
            field=models.PositiveIntegerField(
                default=500000, help_text="Bir oylik to’lov (so’mda)"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="oqituvchi_foiz",
            field=models.PositiveIntegerField(
                default=40, help_text="O’qituvchi foizi (%)"
            ),
        ),
        migrations.CreateModel(
            name="CourseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Kurs nomi")),
                (
                    "price",
                    models.PositiveIntegerField(verbose_name="Oylik narx (so'm)"),
                ),
                (
                    "teacher_percent",
                    models.PositiveSmallIntegerField(
                        default=40, verbose_name="O'qituvchi foizi (%)"
                    ),
                ),
                (
                    "lessons_per_month",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="Oylik darslar soni"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_templates",
                        to="education.category",
                        verbose_name="Bo'lim (fan)",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_templates",
                        to="accounts.center",
                        verbose_name="Markaz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs shabloni",
                "verbose_name_plural": "Kurs shablonlari",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="group",
            name="course_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="education.coursetemplate",
                verbose_name="Kurs shabloni",
            ),
        ),
    ]
