# Generated by Django 5.2.1 on 2026-05-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0057_coursetemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Keldi"),
                    ("late", "Kech qoldi"),
                    ("absent_excused", "Sababli (Kelmadi)"),
                    ("absent_unexcused", "Sababsiz (Kelmadi)"),
                ],
                default="present",
                max_length=20,
                verbose_name="Holati",
            ),
        ),
    ]
