# Generated by Django 5.2.1 on 2026-07-21 04:37

import django.core.validators
import django.db.models.deletion
import education.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_phase10_phone_unique_and_demo"),
        ("education", "0058_alter_attendance_status_late"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField(verbose_name="Savol matni")),
                (
                    "points",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=education.models.exam_upload_path,
                        verbose_name="Qo'shimcha fayl (PDF/rasm)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_questions",
                        to="accounts.center",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bo'sh bo'lsa — butun markaz uchun umumiy savol",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_questions",
                        to="education.group",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_exam_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imtihon savoli",
                "verbose_name_plural": "Imtihon savollari",
                "ordering": ("sort_order", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["center", "is_active"],
                        name="education_e_center__cdcfb0_idx",
                    ),
                    models.Index(
                        fields=["group", "is_active"],
                        name="education_e_group_i_f4d561_idx",
                    ),
                ],
            },
        ),
    ]
