# Generated by Django 5.0.7 on 2026-07-13 16:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0049_center_role_ai_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=80, verbose_name="Nomi")),
                ("narx_som", models.PositiveIntegerField(verbose_name="Narxi (so'm)")),
                ("kun", models.PositiveSmallIntegerField(verbose_name="Muddati (kun)")),
                (
                    "jon_soni",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Bir tiklanishda nechta jon"
                    ),
                ),
                (
                    "soat",
                    models.PositiveSmallIntegerField(
                        verbose_name="Necha soatda bir tiklanadi"
                    ),
                ),
                (
                    "izoh",
                    models.CharField(blank=True, max_length=160, verbose_name="Izoh"),
                ),
                (
                    "tartib",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Tartib"),
                ),
                ("faol", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Tarif",
                "verbose_name_plural": "Tariflar",
                "ordering": ["tartib", "narx_som"],
            },
        ),
        migrations.CreateModel(
            name="DuelInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "holat",
                    models.CharField(
                        choices=[
                            ("kutilmoqda", "Kutilmoqda"),
                            ("qabul", "Qabul qilindi"),
                            ("rad", "Rad etildi"),
                        ],
                        default="kutilmoqda",
                        max_length=12,
                    ),
                ),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                (
                    "kimdan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yuborilgan_chaqiriqlar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kimga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kelgan_chaqiriqlar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Duel chaqirig'i",
                "verbose_name_plural": "Duel chaqiriqlari",
                "ordering": ["-yaratilgan"],
            },
        ),
        migrations.CreateModel(
            name="GameProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("robot", models.BooleanField(default=False, verbose_name="Robot")),
                (
                    "robot_ism",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="Robot ismi"
                    ),
                ),
                (
                    "maxorat",
                    models.FloatField(
                        default=0.7,
                        help_text="Robot 10 ta savoldan o'rtacha shuncha ulushiga to'g'ri javob beradi",
                        verbose_name="Mahorat (0.5–0.9)",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="game/avatar/",
                        verbose_name="Avatar",
                    ),
                ),
                ("xp", models.PositiveIntegerField(default=0, verbose_name="Jami XP")),
                (
                    "hafta_xp",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Shu haftadagi XP"
                    ),
                ),
                (
                    "chaqmoq",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        help_text="O'yin valyutasi. ChaqmoqApp balansidan alohida.",
                        max_digits=9,
                        verbose_name="Chaqmoq",
                    ),
                ),
                (
                    "jon",
                    models.PositiveSmallIntegerField(default=3, verbose_name="Jon"),
                ),
                (
                    "jon_yangilangan",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Jon oxirgi tiklangan vaqt",
                    ),
                ),
                (
                    "jon_kuni",
                    models.DateField(
                        blank=True, null=True, verbose_name="Jon oxirgi tiklangan kun"
                    ),
                ),
                (
                    "streak_kun",
                    models.PositiveIntegerField(default=0, verbose_name="Streak (kun)"),
                ),
                (
                    "oxirgi_oyin_kuni",
                    models.DateField(
                        blank=True, null=True, verbose_name="Oxirgi o'ynagan kun"
                    ),
                ),
                (
                    "liga",
                    models.CharField(
                        choices=[
                            ("bronza", "Bronza"),
                            ("kumush", "Kumush"),
                            ("oltin", "Oltin"),
                            ("olmos", "Olmos"),
                        ],
                        default="bronza",
                        max_length=10,
                        verbose_name="Liga",
                    ),
                ),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.center",
                        verbose_name="Markaz",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi (robot uchun bo'sh)",
                    ),
                ),
            ],
            options={
                "verbose_name": "O'yinchi",
                "verbose_name_plural": "O'yinchilar",
                "ordering": ["-hafta_xp"],
            },
        ),
        migrations.CreateModel(
            name="Duel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raqib_nomi",
                    models.CharField(max_length=120, verbose_name="Raqib nomi"),
                ),
                (
                    "ball",
                    models.PositiveIntegerField(
                        default=0, verbose_name="O'yinchi bali"
                    ),
                ),
                (
                    "raqib_ball",
                    models.PositiveIntegerField(default=0, verbose_name="Raqib bali"),
                ),
                (
                    "togri_javoblar",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="To'g'ri javoblar"
                    ),
                ),
                (
                    "holat",
                    models.CharField(
                        choices=[("davom", "Davom etmoqda"), ("tugagan", "Tugagan")],
                        default="davom",
                        max_length=10,
                    ),
                ),
                (
                    "natija",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("galaba", "G'alaba"),
                            ("maglubiyat", "Mag'lubiyat"),
                            ("durrang", "Durrang"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                (
                    "olingan_xp",
                    models.PositiveIntegerField(default=0, verbose_name="Olingan XP"),
                ),
                (
                    "olingan_chaqmoq",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        verbose_name="Olingan chaqmoq",
                    ),
                ),
                ("boshlangan", models.DateTimeField(auto_now_add=True)),
                ("tugagan", models.DateTimeField(blank=True, null=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.center",
                    ),
                ),
                (
                    "oyinchi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duels",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'yinchi",
                    ),
                ),
                (
                    "raqib",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raqib_duellari",
                        to="game.gameprofile",
                        verbose_name="Raqib",
                    ),
                ),
            ],
            options={
                "verbose_name": "Duel",
                "verbose_name_plural": "Duellar",
                "ordering": ["-boshlangan"],
            },
        ),
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="O'chirilgan"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan sana/vaqt"
                    ),
                ),
                (
                    "deleted_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="O'chirish sababi"
                    ),
                ),
                (
                    "restored_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tiklangan sana/vaqt"
                    ),
                ),
                ("sarlavha", models.CharField(max_length=160, verbose_name="Sarlavha")),
                ("matn", models.TextField(verbose_name="Matn")),
                (
                    "tur",
                    models.CharField(
                        choices=[
                            ("yangilik", "Yangilik"),
                            ("elon", "E'lon"),
                            ("yangilanish", "Ilova yangilanishi"),
                            ("turnir", "Turnir"),
                        ],
                        default="yangilik",
                        max_length=16,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "rasm",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="game/yangiliklar/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "muhim",
                    models.BooleanField(
                        default=False,
                        help_text="Bosh ekranda tepada ko'rsatiladi",
                        verbose_name="Muhim",
                    ),
                ),
                ("faol", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "chop_etilgan",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Chop etilgan sana",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.center",
                        verbose_name="Markaz (bo'sh = umumiy)",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan foydalanuvchi",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tiklagan foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yangilik",
                "verbose_name_plural": "Yangiliklar",
                "ordering": ["-muhim", "-chop_etilgan"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="O'chirilgan"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan sana/vaqt"
                    ),
                ),
                (
                    "deleted_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="O'chirish sababi"
                    ),
                ),
                (
                    "restored_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tiklangan sana/vaqt"
                    ),
                ),
                (
                    "tur",
                    models.CharField(
                        choices=[
                            ("tarjima", "Tarjima — so'zning ma'nosini toping"),
                            ("eshitish", "Eshitish — audioni tinglang"),
                            ("boshliq", "Bo'shliq — gapni to'ldiring"),
                            ("rasm", "Rasm — rasmdagi narsani toping"),
                        ],
                        default="tarjima",
                        max_length=16,
                        verbose_name="Savol turi",
                    ),
                ),
                (
                    "savol",
                    models.CharField(
                        help_text="Masalan: «apple» yoki «I ___ a student»",
                        max_length=255,
                        verbose_name="Savol matni",
                    ),
                ),
                (
                    "togri_javob",
                    models.CharField(max_length=120, verbose_name="To'g'ri javob"),
                ),
                (
                    "notogri_1",
                    models.CharField(
                        max_length=120, verbose_name="Noto'g'ri variant 1"
                    ),
                ),
                (
                    "notogri_2",
                    models.CharField(
                        max_length=120, verbose_name="Noto'g'ri variant 2"
                    ),
                ),
                (
                    "notogri_3",
                    models.CharField(
                        max_length=120, verbose_name="Noto'g'ri variant 3"
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="game/audio/",
                        verbose_name="Audio (eshitish savoli uchun)",
                    ),
                ),
                (
                    "rasm",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="game/rasm/",
                        verbose_name="Rasm (rasm savoli uchun)",
                    ),
                ),
                (
                    "izoh",
                    models.CharField(
                        blank=True,
                        help_text="Javobdan keyin o'quvchiga ko'rsatiladi",
                        max_length=255,
                        verbose_name="Qoida / izoh",
                    ),
                ),
                ("faol", models.BooleanField(default=True, verbose_name="Faol")),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.center",
                        verbose_name="Markaz (bo'sh = umumiy)",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan foydalanuvchi",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tiklagan foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savol",
                "verbose_name_plural": "Savollar",
                "ordering": ["-yaratilgan"],
            },
        ),
        migrations.CreateModel(
            name="DuelQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tartib", models.PositiveSmallIntegerField()),
                ("variantlar", models.JSONField(default=list)),
                ("tanlangan", models.CharField(blank=True, default="", max_length=120)),
                ("togri", models.BooleanField(blank=True, null=True)),
                ("sarflangan_ms", models.PositiveIntegerField(default=0)),
                ("olingan_ball", models.PositiveIntegerField(default=0)),
                ("raqib_togri", models.BooleanField(default=False)),
                ("raqib_ms", models.PositiveIntegerField(default=0)),
                ("raqib_ball", models.PositiveIntegerField(default=0)),
                ("javob_berilgan", models.DateTimeField(blank=True, null=True)),
                (
                    "duel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savollar",
                        to="game.duel",
                    ),
                ),
                (
                    "savol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.question"
                    ),
                ),
            ],
            options={
                "verbose_name": "Duel savoli",
                "verbose_name_plural": "Duel savollari",
                "ordering": ["tartib"],
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="O'chirilgan"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan sana/vaqt"
                    ),
                ),
                (
                    "deleted_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="O'chirish sababi"
                    ),
                ),
                (
                    "restored_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tiklangan sana/vaqt"
                    ),
                ),
                ("nom", models.CharField(max_length=120, verbose_name="Nomi")),
                (
                    "daraja",
                    models.CharField(
                        choices=[
                            ("A1", "A1 — Boshlang'ich"),
                            ("A2", "A2 — Elementar"),
                            ("B1", "B1 — O'rta"),
                            ("B2", "B2 — O'rtadan yuqori"),
                            ("C1", "C1 — Ilg'or"),
                        ],
                        default="A1",
                        max_length=2,
                        verbose_name="Daraja",
                    ),
                ),
                ("izoh", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "tartib",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                ("faol", models.BooleanField(default=True, verbose_name="Faol")),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.center",
                        verbose_name="Markaz (bo'sh = umumiy)",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan foydalanuvchi",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tiklagan foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savollar to'plami",
                "verbose_name_plural": "Savollar to'plamlari",
                "ordering": ["tartib", "daraja", "nom"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="kategoriya",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="game.questioncategory",
                verbose_name="To'plam",
            ),
        ),
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="O'chirilgan"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan sana/vaqt"
                    ),
                ),
                (
                    "deleted_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="O'chirish sababi"
                    ),
                ),
                (
                    "restored_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tiklangan sana/vaqt"
                    ),
                ),
                ("nom", models.CharField(max_length=120, verbose_name="Nomi")),
                (
                    "izoh",
                    models.CharField(blank=True, max_length=200, verbose_name="Izoh"),
                ),
                (
                    "tur",
                    models.CharField(
                        choices=[
                            ("avatar", "Avatar"),
                            ("ramka", "Ramka"),
                            ("assesuar", "Aksessuar"),
                            ("jon", "Jon to'plami"),
                        ],
                        default="assesuar",
                        max_length=16,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "rasm",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="game/dokon/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "narx_chaqmoq",
                    models.DecimalField(
                        decimal_places=1, max_digits=7, verbose_name="Narxi (chaqmoq)"
                    ),
                ),
                (
                    "beradigan_jon",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Beradigan jon"
                    ),
                ),
                (
                    "zaxira",
                    models.IntegerField(
                        default=-1, help_text="-1 = cheksiz", verbose_name="Zaxira"
                    ),
                ),
                ("faol", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "tartib",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.center",
                        verbose_name="Markaz (bo'sh = umumiy)",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan foydalanuvchi",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tiklagan foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Do'kon mahsuloti",
                "verbose_name_plural": "Do'kon mahsulotlari",
                "ordering": ["tartib", "narx_chaqmoq"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "narx_chaqmoq",
                    models.DecimalField(
                        decimal_places=1, max_digits=7, verbose_name="To'langan chaqmoq"
                    ),
                ),
                ("sana", models.DateTimeField(auto_now_add=True)),
                (
                    "topshirildi",
                    models.BooleanField(default=False, verbose_name="Topshirildi"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_xaridlar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="xaridlar",
                        to="game.shopitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xarid",
                "verbose_name_plural": "Xaridlar",
                "ordering": ["-sana"],
            },
        ),
        migrations.CreateModel(
            name="Obuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boshlangan",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Boshlangan"
                    ),
                ),
                ("tugaydi", models.DateTimeField(verbose_name="Tugaydi")),
                (
                    "tolangan",
                    models.BooleanField(default=False, verbose_name="To'langan"),
                ),
                (
                    "izoh",
                    models.CharField(blank=True, max_length=160, verbose_name="Izoh"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_obunalar",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'quvchi",
                    ),
                ),
                (
                    "tarif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.tarif",
                        verbose_name="Tarif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obuna",
                "verbose_name_plural": "Obunalar",
                "ordering": ["-boshlangan"],
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "holat",
                    models.CharField(
                        choices=[
                            ("kutilmoqda", "Kutilmoqda"),
                            ("qabul", "Qabul qilindi"),
                            ("rad", "Rad etildi"),
                        ],
                        default="kutilmoqda",
                        max_length=12,
                    ),
                ),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                (
                    "kimdan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yuborilgan_dostliklar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kimga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kelgan_dostliklar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Do'stlik",
                "verbose_name_plural": "Do'stliklar",
                "ordering": ["-yaratilgan"],
                "unique_together": {("kimdan", "kimga")},
            },
        ),
        migrations.AddIndex(
            model_name="gameprofile",
            index=models.Index(
                fields=["robot", "hafta_xp"], name="game_gamepr_robot_d6e15a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="duelquestion",
            unique_together={("duel", "tartib")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["faol", "center"], name="game_questi_faol_bd8b92_idx"
            ),
        ),
    ]
