# Generated by Django 5.0.7 on 2026-07-14 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_center_role_ai_enabled"),
        ("game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gameprofile",
            name="oxirgi_faol",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Oxirgi faollik"
            ),
        ),
        migrations.AddIndex(
            model_name="gameprofile",
            index=models.Index(
                fields=["oxirgi_faol"], name="game_gamepr_oxirgi__f5de60_idx"
            ),
        ),
    ]
