# Generated by Django 5.0.7 on 2026-07-25 18:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_phase10_phone_unique_and_demo"),
        ("game", "0002_gameprofile_oxirgi_faol_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="O'chirilgan"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan sana/vaqt"
                    ),
                ),
                (
                    "deleted_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="O'chirish sababi"
                    ),
                ),
                (
                    "restored_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tiklangan sana/vaqt"
                    ),
                ),
                ("nom", models.CharField(max_length=80, verbose_name="O'yin nomi")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Bo'sh qoldirsangiz nomdan avtomatik yasaladi.",
                        max_length=90,
                        unique=True,
                        verbose_name="Kod nomi",
                    ),
                ),
                (
                    "motor",
                    models.CharField(
                        choices=[
                            (
                                "duel",
                                "⚔️ Duel — Raqib bilan yonma-yon poyga — kim ko'proq to'g'ri javob beradi.",
                            ),
                            (
                                "viktorina",
                                "🧠 Viktorina — Yakka o'yin: savollarga vaqt ichida javob bering.",
                            ),
                            (
                                "omon_qol",
                                "🛡️ Omon qol — Xato qilsangiz jon ketadi. Jonlar tugaguncha davom etadi.",
                            ),
                            (
                                "sprint",
                                "⚡ Sprint — Belgilangan vaqt ichida imkon qadar ko'p to'g'ri javob.",
                            ),
                            (
                                "xotira",
                                "🃏 Xotira — So'z va tarjimasini yopiq kartalar orasidan toping.",
                            ),
                            (
                                "juftlash",
                                "🔗 Juftlash — Chap ustundagi so'zni o'ng ustundagi tarjimasiga ulang.",
                            ),
                        ],
                        help_text="O'yin qanday o'ynalishi. Ilovada shu mexanika ekrani ochiladi.",
                        max_length=32,
                        verbose_name="Mexanika (motor)",
                    ),
                ),
                (
                    "izoh",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Qisqa izoh"
                    ),
                ),
                (
                    "yoriqnoma",
                    models.CharField(
                        blank=True,
                        help_text="Bo'sh qoldirsangiz motorning standart qoidasi ishlatiladi.",
                        max_length=255,
                        verbose_name="Qoida",
                    ),
                ),
                (
                    "ikonka",
                    models.CharField(
                        blank=True,
                        help_text="Masalan: 🧠 ⚡ 🃏. Bo'sh bo'lsa motor ikonkasi olinadi.",
                        max_length=8,
                        verbose_name="Ikonka (emoji)",
                    ),
                ),
                (
                    "rang",
                    models.CharField(
                        blank=True,
                        help_text="Masalan: #0EA5E9. Bo'sh bo'lsa motor rangi olinadi.",
                        max_length=7,
                        verbose_name="Rang (HEX)",
                    ),
                ),
                (
                    "rasm",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="game/oyinlar/",
                        verbose_name="Muqova rasmi",
                    ),
                ),
                (
                    "daraja",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A1", "A1 — Boshlang'ich"),
                            ("A2", "A2 — Elementar"),
                            ("B1", "B1 — O'rta"),
                            ("B2", "B2 — O'rtadan yuqori"),
                            ("C1", "C1 — Ilg'or"),
                        ],
                        help_text="Bo'sh = daraja bo'yicha cheklanmaydi.",
                        max_length=2,
                        verbose_name="Daraja filtri",
                    ),
                ),
                (
                    "savollar_soni",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Savollar soni"
                    ),
                ),
                (
                    "savol_soniya",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="0 = savolga alohida taymer yo'q (Sprint/Xotira kabi o'yinlarda).",
                        verbose_name="Bitta savolga soniya",
                    ),
                ),
                (
                    "jon_narxi",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="0 = bepul, jon talab qilinmaydi.",
                        verbose_name="Necha jon sarflaydi",
                    ),
                ),
                (
                    "xp_mukofot",
                    models.PositiveSmallIntegerField(
                        default=40,
                        help_text="Aniqlikka mutanosib beriladi: 8/10 to'g'ri → 80%.",
                        verbose_name="To'liq bajarilganda XP",
                    ),
                ),
                (
                    "chaqmoq_koef",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("1.0"),
                        help_text="Standart mukofot shunga ko'paytiriladi (1.0 = duel bilan bir xil).",
                        max_digits=4,
                        verbose_name="Chaqmoq koeffitsiyenti",
                    ),
                ),
                (
                    "sozlamalar",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Motorga xos sozlamalar, masalan Sprint uchun {"davomiylik_soniya": 60}. Bo\'sh qoldirsangiz standart qiymat ishlatiladi.',
                        verbose_name="Qo'shimcha sozlamalar",
                    ),
                ),
                (
                    "faqat_pro",
                    models.BooleanField(
                        default=False, verbose_name="Faqat Pro (tarifli) o'quvchilarga"
                    ),
                ),
                ("faol", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "tartib",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Tartib"),
                ),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.center",
                        verbose_name="Markaz (bo'sh = barcha markazlarga)",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan foydalanuvchi",
                    ),
                ),
                (
                    "kategoriyalar",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Bo'sh = barcha to'plamlardan savol olinadi.",
                        related_name="oyinlar",
                        to="game.questioncategory",
                        verbose_name="Savollar to'plamlari",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_%(class)s_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tiklagan foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "O'yin",
                "verbose_name_plural": "O'yinlar (katalog)",
                "ordering": ["tartib", "nom"],
            },
        ),
        migrations.AddField(
            model_name="duel",
            name="mode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duellar",
                to="game.gamemode",
                verbose_name="O'yin (katalog)",
            ),
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oyin_nomi",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="O'yin nomi"
                    ),
                ),
                (
                    "motor",
                    models.CharField(blank=True, max_length=32, verbose_name="Motor"),
                ),
                (
                    "jami_savol",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Berilgan savollar"
                    ),
                ),
                (
                    "togri_javoblar",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="To'g'ri javoblar"
                    ),
                ),
                (
                    "xato_javoblar",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Xato javoblar"
                    ),
                ),
                ("ball", models.PositiveIntegerField(default=0, verbose_name="Ball")),
                (
                    "olingan_xp",
                    models.PositiveIntegerField(default=0, verbose_name="Olingan XP"),
                ),
                (
                    "olingan_chaqmoq",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=6,
                        verbose_name="Olingan chaqmoq",
                    ),
                ),
                (
                    "holat",
                    models.CharField(
                        choices=[("davom", "Davom etmoqda"), ("tugagan", "Tugagan")],
                        default="davom",
                        max_length=10,
                    ),
                ),
                ("boshlangan", models.DateTimeField(auto_now_add=True)),
                ("tugagan", models.DateTimeField(blank=True, null=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.center",
                    ),
                ),
                (
                    "mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessiyalar",
                        to="game.gamemode",
                        verbose_name="O'yin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessiyalar",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'yinchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "O'yin sessiyasi",
                "verbose_name_plural": "O'yin sessiyalari",
                "ordering": ["-boshlangan"],
            },
        ),
        migrations.CreateModel(
            name="GameSessionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tartib", models.PositiveSmallIntegerField()),
                ("variantlar", models.JSONField(default=list)),
                ("tanlangan", models.CharField(blank=True, default="", max_length=120)),
                ("togri", models.BooleanField(blank=True, null=True)),
                ("sarflangan_ms", models.PositiveIntegerField(default=0)),
                ("olingan_ball", models.PositiveIntegerField(default=0)),
                ("javob_berilgan", models.DateTimeField(blank=True, null=True)),
                (
                    "savol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.question"
                    ),
                ),
                (
                    "sessiya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savollar",
                        to="game.gamesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessiya savoli",
                "verbose_name_plural": "Sessiya savollari",
                "ordering": ["tartib"],
            },
        ),
        migrations.AddIndex(
            model_name="gamemode",
            index=models.Index(
                fields=["faol", "center"], name="game_gamemo_faol_2a6491_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gamesession",
            index=models.Index(
                fields=["user", "holat"], name="game_gamese_user_id_350494_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gamesessionquestion",
            unique_together={("sessiya", "tartib")},
        ),
    ]
