# Generated by Django 5.0.7 on 2026-07-27 06:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_phase10_phone_unique_and_demo"),
        ("game", "0003_gamemode_duel_mode_gamesession_gamesessionquestion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="duel",
            name="juft",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="juft_teskari",
                to="game.duel",
                verbose_name="Juft duel",
            ),
        ),
        migrations.AddField(
            model_name="duel",
            name="pvp",
            field=models.BooleanField(default=False, verbose_name="Odam bilan duel"),
        ),
        migrations.AddField(
            model_name="tarif",
            name="chaqmoq_bonus_foiz",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Har o'yindan olinadigan chaqmoq shuncha foizga ko'payadi. Masalan 50 → 4 chaqmoq o'rniga 6. Jarima bonussiz qoladi.",
                verbose_name="Chaqmoq bonusi (%)",
            ),
        ),
        migrations.AddField(
            model_name="tarif",
            name="oyin_qulf_soat",
            field=models.PositiveSmallIntegerField(
                default=24,
                help_text="Bepul rejada 24 soat. 0 = qulflanmaydi.",
                verbose_name="O'ynalgan o'yin necha soatdan keyin ochiladi",
            ),
        ),
        migrations.AlterField(
            model_name="tarif",
            name="soat",
            field=models.PositiveSmallIntegerField(
                help_text="Bepul rejada 8 soat.",
                verbose_name="Jonlar necha soatda tiklanadi",
            ),
        ),
        migrations.CreateModel(
            name="DuelQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "holat",
                    models.CharField(
                        choices=[
                            ("kutmoqda", "Raqib kutilmoqda"),
                            ("topildi", "Raqib topildi"),
                            ("bekor", "Bekor qilindi"),
                        ],
                        default="kutmoqda",
                        max_length=10,
                    ),
                ),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.center",
                    ),
                ),
                (
                    "duel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navbat_yozuvlari",
                        to="game.duel",
                    ),
                ),
                (
                    "mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navbatlar",
                        to="game.gamemode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duel_navbatlari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Duel navbati",
                "verbose_name_plural": "Duel navbati",
                "ordering": ["yaratilgan"],
                "indexes": [
                    models.Index(
                        fields=["holat", "mode", "yaratilgan"],
                        name="game_duelqu_holat_a43aab_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tur",
                    models.CharField(
                        choices=[
                            ("shikoyat", "Shikoyat"),
                            ("taklif", "Taklif"),
                            ("xato", "Xatolik haqida xabar"),
                        ],
                        default="taklif",
                        max_length=12,
                        verbose_name="Turi",
                    ),
                ),
                ("matn", models.TextField(verbose_name="Xabar matni")),
                (
                    "aloqa",
                    models.CharField(
                        blank=True,
                        help_text="Telefon yoki Telegram",
                        max_length=120,
                        verbose_name="Aloqa uchun",
                    ),
                ),
                (
                    "holat",
                    models.CharField(
                        choices=[
                            ("yangi", "Yangi"),
                            ("korildi", "Ko'rib chiqilmoqda"),
                            ("hal", "Hal qilindi"),
                        ],
                        default="yangi",
                        max_length=10,
                        verbose_name="Holat",
                    ),
                ),
                ("javob", models.TextField(blank=True, verbose_name="Javob")),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                ("javob_berilgan", models.DateTimeField(blank=True, null=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.center",
                    ),
                ),
                (
                    "mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="murojaatlar",
                        to="game.gamemode",
                        verbose_name="Qaysi o'yin haqida",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_murojaatlar",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kimdan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Murojaat (shikoyat/taklif)",
                "verbose_name_plural": "Murojaatlar (shikoyat/taklif)",
                "ordering": ["-yaratilgan"],
                "indexes": [
                    models.Index(
                        fields=["holat", "-yaratilgan"],
                        name="game_feedba_holat_2b23e0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GameCooldown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oxirgi_oynalgan",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oxirgi o'ynalgan",
                    ),
                ),
                (
                    "mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qulflar",
                        to="game.gamemode",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qulflar",
                        to="game.gameprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "O'yin qulfi",
                "verbose_name_plural": "O'yin qulflari",
                "indexes": [
                    models.Index(
                        fields=["profile", "oxirgi_oynalgan"],
                        name="game_gameco_profile_7d7e82_idx",
                    )
                ],
                "unique_together": {("profile", "mode")},
            },
        ),
        migrations.CreateModel(
            name="TarifSorovi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usul",
                    models.CharField(
                        choices=[
                            ("click", "Click (onlayn)"),
                            ("naqd", "Naqd / qo'lda tasdiqlash"),
                        ],
                        max_length=8,
                        verbose_name="To'lov usuli",
                    ),
                ),
                (
                    "holat",
                    models.CharField(
                        choices=[
                            ("kutilmoqda", "To'lov kutilmoqda"),
                            ("tolangan", "To'landi"),
                            ("bekor", "Bekor qilindi"),
                        ],
                        default="kutilmoqda",
                        max_length=12,
                        verbose_name="Holat",
                    ),
                ),
                ("narx_som", models.PositiveIntegerField(verbose_name="Summa (so'm)")),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "izoh",
                    models.CharField(blank=True, max_length=200, verbose_name="Izoh"),
                ),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                ("tasdiqlangan", models.DateTimeField(blank=True, null=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.center",
                    ),
                ),
                (
                    "obuna",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sorovlar",
                        to="game.obuna",
                        verbose_name="Yoqilgan obuna",
                    ),
                ),
                (
                    "tarif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.tarif",
                        verbose_name="Tarif",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_tarif_sorovlari",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif so'rovi",
                "verbose_name_plural": "Tarif so'rovlari",
                "ordering": ["-yaratilgan"],
                "indexes": [
                    models.Index(
                        fields=["holat", "-yaratilgan"],
                        name="game_tarifs_holat_2bff75_idx",
                    )
                ],
            },
        ),
    ]
