# Generated by Django 5.0.7 on 2025-08-29 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('tur', models.CharField(choices=[('plus', '+ Chaqmoq'), ('minus', '− Chaqmoq')], max_length=10)),
                ('min_baho', models.PositiveSmallIntegerField(default=1)),
                ('max_baho', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Chaqmoq qoida',
                'verbose_name_plural': 'Chaqmoq qoidalari',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.SmallIntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('beruvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaqmoq_beruvchi', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.group')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chaqmoq.rule')),
            ],
            options={
                'verbose_name': 'Chaqmoq yozuvi',
                'verbose_name_plural': 'Chaqmoq yozuvlari',
            },
        ),
    ]
