# Generated by Django 5.0.7 on 2025-10-30 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('tur', models.CharField(choices=[('plus', '+ Chaqmoq'), ('minus', '− Chaqmoq')], max_length=10)),
                ('min_baho', models.PositiveSmallIntegerField(default=1)),
                ('max_baho', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Chaqmoq qoida',
                'verbose_name_plural': 'Chaqmoq qoidalari',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.SmallIntegerField()),
                ('sana', models.DateTimeField(default=django.utils.timezone.now)),
                ('beruvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaqmoq_beruvchi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chaqmoq yozuvi',
                'verbose_name_plural': 'Chaqmoq yozuvlari',
            },
        ),
    ]
