# Generated by Django 5.0.7 on 2025-10-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaqmoq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['-sana'], 'verbose_name': 'Chaqmoq yozuvi', 'verbose_name_plural': 'Chaqmoq yozuvlari'},
        ),
        migrations.AlterField(
            model_name='ledger',
            name='sana',
            field=models.DateField(db_index=True, verbose_name='Sana'),
        ),
    ]
