# Generated by Django 5.0.7 on 2025-10-30 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chaqmoq', '0001_initial'),
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.group'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledger',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chaqmoq.rule'),
        ),
    ]
