# Generated by Django 5.0.7 on 2025-10-17 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaqmoq', '0002_alter_ledger_options_alter_ledger_sana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'verbose_name': 'Chaqmoq yozuvi', 'verbose_name_plural': 'Chaqmoq yozuvlari'},
        ),
        migrations.AlterField(
            model_name='ledger',
            name='sana',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
