# Generated by Django 5.0.7 on 2026-01-19 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaqmoq', '0003_ledger_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='rule_max_baho',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='rule_min_baho',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='rule_nom',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ledger',
            name='rule_tur',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chaqmoq.rule'),
        ),
    ]
