# Generated by Django 5.0.7 on 2026-01-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_center_features'),
        ('chaqmoq', '0004_ledger_rule_max_baho_ledger_rule_min_baho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.center'),
        ),
    ]
