# Generated by Django 5.0.7 on 2026-01-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaqmoq', '0005_rule_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='can_director',
            field=models.BooleanField(default=True, verbose_name='Director ishlata oladi'),
        ),
        migrations.AddField(
            model_name='rule',
            name='can_manager',
            field=models.BooleanField(default=True, verbose_name='Manager ishlata oladi'),
        ),
        migrations.AddField(
            model_name='rule',
            name='can_teacher',
            field=models.BooleanField(default=True, verbose_name="O'qituvchi ishlata oladi"),
        ),
    ]
