# Generated by Django 5.0.7 on 2026-03-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaqmoq', '0006_rule_can_director_rule_can_manager_rule_can_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='absence_limit',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True, verbose_name='Sababsiz qoldirish limiti'),
        ),
        migrations.AddField(
            model_name='rule',
            name='lightning_penalty',
            field=models.SmallIntegerField(blank=True, default=-5, null=True, verbose_name='Ayiriladigan chaqmoq'),
        ),
        migrations.AddField(
            model_name='rule',
            name='payment_bonus_lightning',
            field=models.SmallIntegerField(blank=True, default=5, null=True, verbose_name="To'lov uchun bonus chaqmoq"),
        ),
        migrations.AddField(
            model_name='rule',
            name='period',
            field=models.CharField(blank=True, choices=[('monthly', 'Oylik')], default='monthly', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='tur',
            field=models.CharField(choices=[('plus', '+ Chaqmoq'), ('minus', '− Chaqmoq'), ('attendance_penalty', 'Davomat jarimasi'), ('payment_bonus', 'To‘lov bonusi')], max_length=50),
        ),
    ]
