# Generated by Django 5.0.7 on 2026-03-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaqmoq', '0007_rule_absence_limit_rule_lightning_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='lightning_bonus',
            field=models.SmallIntegerField(blank=True, default=10, null=True, verbose_name="Qo'shiladigan chaqmoq"),
        ),
        migrations.AddField(
            model_name='rule',
            name='presence_limit',
            field=models.PositiveSmallIntegerField(blank=True, default=12, null=True, verbose_name='Darsga kelish limiti'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='tur',
            field=models.CharField(choices=[('plus', '+ Chaqmoq'), ('minus', '− Chaqmoq'), ('attendance_penalty', 'Davomat jarimasi'), ('attendance_bonus', 'Davomat bonusi'), ('payment_bonus', 'To‘lov bonusi')], max_length=50),
        ),
    ]
