# Generated by Django 5.0.7 on 2026-03-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaqmoq', '0008_rule_lightning_bonus_rule_presence_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='rule_tur',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
