# Generated by Django 5.0.7 on 2026-03-16 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaqmoq', '0009_alter_ledger_rule_tur'),
        ('education', '0031_teacherincome_center_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('attendance', 'Davomat'), ('bonus', 'Bonus'), ('penalty', 'Jarima'), ('manual', 'Boshqa')], default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightning_history', to='education.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chaqmoq tarixi',
                'verbose_name_plural': 'Chaqmoq tarixlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
