# Generated by Django 5.2.1 on 2026-04-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaqmoq", "0010_lightninghistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="related_month",
            field=models.DateField(blank=True, null=True, verbose_name="Tegishli oy"),
        ),
        migrations.AddField(
            model_name="rule",
            name="discipline_active",
            field=models.BooleanField(default=False, verbose_name="Qoida faolmi?"),
        ),
        migrations.AddField(
            model_name="rule",
            name="discipline_bonus_score",
            field=models.SmallIntegerField(
                default=5, verbose_name="Deadline gacha to'lov bonusi"
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="discipline_deadline_day",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Deadline sanasi (oyning sanasi)"
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="discipline_penalty_score",
            field=models.SmallIntegerField(
                default=-10, verbose_name="Dedline gacha to'lov qilmaganlarga jarima"
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="tur",
            field=models.CharField(
                choices=[
                    ("plus", "+ Chaqmoq"),
                    ("minus", "− Chaqmoq"),
                    ("attendance_penalty", "Davomat jarimasi"),
                    ("attendance_bonus", "Davomat bonusi"),
                    ("payment_bonus", "To‘lov bonusi"),
                    ("payment_discipline", "To‘lov intizomi"),
                ],
                max_length=50,
            ),
        ),
    ]
